### ISSUE TITLE
协同文档支持下载吗?这个功能可有？

### ISSUE THREAD

**Issue by JackFrancisLiu** [red-axe/am-editor#100]
协同文档支持下载吗?这个功能可有？

**Comment by yanmao-cc** [comment]
文档下载，就是导出，可以使用 engine.getHtml 获取到 html ，然后把 html 交给后端转换成文件再导出

**Comment by byoungd** [comment]
我们内部已经有了下载为word和pdf的实现吗，但是该功能需要涉及到一些代码需要脱敏，后续会考虑发布。





------------------ 原始邮件 ------------------
发件人: YiYang ***@***.***&gt;
发送时间: 2022年2月21日 09:57
收件人: red-axe/am-editor ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [red-axe/am-editor] 协同文档支持下载吗?这个功能可有？ (Issue #100)

**Comment by JackFrancisLiu** [comment]
> 文档下载，就是导出，可以使用 engine.getHtml 获取到 html ，然后把 html 交给后端转换成文件再导出

ok，感谢

**Comment by JackFrancisLiu** [comment]
> 文档下载，就是导出，可以使用 engine.getHtml 获取到 html ，然后把 html 交给后端转换成文件再导出

再请问一下最多支持多少人在线？   支持多大的文件协同编辑？

**Comment by JackFrancisLiu** [comment]
> 我们内部已经有了下载为word和pdf的实现吗，但是该功能需要涉及到一些代码需要脱敏，后续会考虑发布。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: YiYang ***@***.***&gt; 发送时间: 2022年2月21日 09:57 收件人: red-axe/am-editor ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [red-axe/am-editor] 协同文档支持下载吗?这个功能可有？ (Issue #100)

感谢！

**Comment by starsoul666** [comment]
> 我们内部已经有了下载为word和pdf的实现吗，但是该功能需要涉及到一些代码需要脱敏，后续会考虑发布。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: YiYang ***@***.***&gt; 发送时间: 2022年2月21日 09:57 收件人: red-axe/am-editor ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [red-axe/am-editor] 协同文档支持下载吗?这个功能可有？ (Issue #100)

这个功能可以用了吗？
