### ISSUE TITLE
协同光标显示人员

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#101]
作者，你好！我想问一下，这个协同光标是需要自己封装还是说提供了api的呢？

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/tree/master/ot-server
https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/ot/client.ts
在engine中会对这些数据处理，生成用户的协同光标
https://github.com/red-axe/am-editor/blob/master/packages/engine/src/ot/range-coloring.ts
