### ISSUE TITLE
图片上传前想压缩后再上传要怎么配置？

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
想在图片上传的时候增加一个压缩后再上传

**Comment by yanmao-cc** [comment]
看看这里 https://editor.aomao.com/zh-CN/config/upload 有没有能用上的

**Comment by chunyangyang** [comment]
> 看看这里 https://editor.aomao.com/zh-CN/config/upload 有没有能用上的

我使用了@aomao/plugin-image,
![image](https://user-images.githubusercontent.com/20843521/158347942-021e7fc5-3165-47c5-9ca6-effbaeba5b6e.png)
看了源码，没有提供上传前的钩子，建议提供一个

**Comment by chunyangyang** [comment]
> https://editor.aomao.com/zh-CN/config/upload#%E5%8D%95%E4%B8%AA%E6%8F%92%E4%BB%B6%E4%B8%8A%E4%BC%A0 这里可以通过继承来实现重写

可以了谢谢!
示例的base64占位显示插入有问题，建议更新
