### ISSUE TITLE
表格卡片会在某种情况下readonly下一直loading的情况

### ISSUE THREAD

**Issue by zhaodeezhu** [red-axe/am-editor#106]
可能是在表格比较多的时候就会这样
![image](https://user-images.githubusercontent.com/58294623/157244530-150c2da9-59b2-43b8-939c-2cca42f5840f.png)

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/157246801-fec9ab23-8c5d-403d-ab2f-3e1736176959.png)
可以看一下你的 scrollNode 节点的高度，因为表格默认开启了懒加载，只会在视界里面内渲染 [layz](https://editor.aomao.com/zh-CN/config#lazyrender)
