### ISSUE TITLE
编辑模式下插入卡片（如：代码块，表格）之后接着编写页面将无法获取焦点

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
1.在添加的卡片
2.在卡片下面接着继续编写文章无法获取焦点
期望可以获取到焦点！
页面如图：点击箭头位置无法获取焦点
![image](https://user-images.githubusercontent.com/20843521/158570370-6d1e3c2d-2580-49c4-9585-3856cb761a4c.png)

**Comment by yanmao-cc** [comment]
我理解是没有新的一行是吗？
1. 单击这类卡片的左右两边是有光标的，然后回车可以到下一行
2. 给编辑区域添加一个 padding 样式，单击padding区域如果是有这种卡片会自动添加新行
![image](https://user-images.githubusercontent.com/55792257/158571592-485321fe-1009-4dd3-bd84-c123e867f63f.png)

**Comment by byoungd** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** 1.在添加的卡片 2.在卡片下面接着继续编写文章无法获取焦点 期望可以获取到焦点！ 页面如图：点击箭头位置无法获取焦点 ![image](https://user-images.githubusercontent.com/20843521/158570370-6d1e3c2d-2580-49c4-9585-3856cb761a4c.png)

这个问题是否已经解决，如果方便的话，请给我们反馈一下，谢谢。

**Comment by chunyangyang** [comment]
已解决
