### ISSUE TITLE
协同光标渲染用户选区错误

### ISSUE THREAD

**Issue by keepfit123** [red-axe/am-editor#114]
![image](https://user-images.githubusercontent.com/98519430/158572938-08df32b6-2564-4f96-9c06-9a6314e260fb.png)
  console.log('body',body)
          // 如果接收者和发送者不是同一人就触发一个message事件，外部可以监听这个事件并作出响应
          if (uuid !== this.current?.uuid) {
            switch (type) {
              case 'select':
               this.engine.ot.renderSelection(body)

**Comment by keepfit123** [comment]
![image](https://user-images.githubusercontent.com/98519430/158573233-c570e8ba-4a0c-4bc8-bde3-bc5f039f6dba.png)

**Comment by yanmao-cc** [comment]
你的用户信息的 name 应该不是个字符串吧？

**Comment by keepfit123** [comment]
是的，name 搞错了（uid要不同区分），问题解决了。
