### ISSUE TITLE
附件下载

### ISSUE THREAD

**Issue by alpschan** [red-axe/am-editor#115]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alpschan** [comment]
附件的下载按钮在哪里配置的呢？

**Comment by yanmao-cc** [comment]
上传接口有返回 download 属性就会有下载链接 https://editor.aomao.com/zh-CN/plugin/plugin-file#%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE

除此之外就是继承 FileComponent 重写 toolbar 方法

**Comment by yanmao-cc** [comment]
继承：
```ts
import { FileComponent } from '@aomao/plugin-file'

export default class extends FileComponent {
  toolbar(){
   const toolbars = super.toolbar()
   return toolbars.filter(item => !item.content.includes('data-icon-download'))
  }
}
```
最后使用新的类替换new Engine中配置在cards中的 FileComponent 类
