### ISSUE TITLE
自定义卡片怎么添加到toolbar的collapse中？

### ISSUE THREAD

**Issue by alpschan** [red-axe/am-editor#116]

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/config/toolbar#groups

**Comment by alpschan** [comment]
在编辑区域输入'/'时，弹出来的和toolbar里面的不一致。自定义的还是无法在'/'出现

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/config.tsx#L327

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/config/toolbar#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%BC%B9%E5%87%BA%E5%B7%A5%E5%85%B7%E6%A0%8F
