### ISSUE TITLE
从表格中离开不触发 onBlur 

### ISSUE THREAD

**Issue by ly01112020** [red-axe/am-editor#118]
多编辑器，光标在单元格中，失去焦点不触发 onBlur 事件

**Comment by ly01112020** [comment]
这个问题没解决吗？
![image](https://user-images.githubusercontent.com/4043937/163744412-c335abe7-42d6-4ede-8d86-37647543a72b.png)

**Comment by ly01112020** [comment]
当前版本 2.8.20  @yanmao-cc

**Comment by yanmao-cc** [comment]
这样还是在焦点内的，就没有 blur 事件。你想实现什么需求？

**Comment by ly01112020** [comment]
两个编辑器，都有表格，|
1.第一个编辑器的单元格中输入东西.
2.然后点击第二个编辑器中的表格，
这个时候第一个编辑器没有触发失去焦点事件，而且第一个编辑器的表格tools还显示，看上图

**Comment by yanmao-cc** [comment]
其它插件升级了吗？我这里没办法复现

**Comment by ly01112020** [comment]
[demo1.zip](https://github.com/red-axe/am-editor/files/8509217/demo1.zip)
![image](https://user-images.githubusercontent.com/4043937/163906576-9bec92b3-a9c5-4644-aefe-452e705bb59b.png)

cd demo1
yarn 
yarn start

**Comment by ly01112020** [comment]
@yanmao-cc

**Comment by yanmao-cc** [comment]
2.8.21
