### ISSUE TITLE
想问一下 plugin-table 这个插件，选中表格的时候怎么才能把那个最大化的按钮给去掉呀

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#119]

**Comment by yanmao-cc** [comment]
可以继承 TableComponent 类，重写 toolbar 方法

```ts
toolbar() {
 const itmes = super.toolbar();
return items.filter(item => item.type !== 'maximize');
}
```

**Comment by huangyuzai** [comment]
> 可以继承 TableComponent 类，重写 toolbar 方法
> 
> ```ts
> toolbar() {
>  const itmes = super.toolbar();
> return items.filter(item => item.type !== 'maximize');
> }
> ```

谢谢大哥，搞定了

**Comment by frontend-qin** [comment]
toolbar() {
 const itmes = super.toolbar();
return items.filter(item => item.type !== 'maximize');
}
这个具体怎么写呢，新手，继承了还一直报错，文档写的也挺简单的
