### ISSUE TITLE
可不可以改写 plugin-table 插件的填充颜色按钮事件

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#121]
把编辑器套在antd表单里面，选中表格时，点击填充单元格背景颜色的那个按钮会触发表单的submit事件，我想禁止掉这个按钮的默认行为，不知道支不支持呢

**Comment by yanmao-cc** [comment]
继承 TableComponent 类，重写 toolbar 方法
```ts
toolbar() {
  const itmes = super.toolbar();
  const colorBtn = items.find(item => item.type === 'node')
  colorBtn?.didMount = (node => {
    node.on('mousedown', e => {
       e.preventDefault()
    })
  })
  return items.filter(item => item.type !== 'maximize');
}
```

**Comment by huangyuzai** [comment]
> 继承 TableComponent 类，重写 toolbar 方法
> 
> ```ts
> toolbar() {
>   const itmes = super.toolbar();
>   const colorBtn = items.find(item => item.type === 'node' && item.node.hasClass('table-color-dropdown-trigger'))
>   colorBtn?.didMount = (node => {
>     node.on('mousedown', e => {
>        e.preventDefault()
>     })
>   })
>   return items.filter(item => item.type !== 'maximize');
> }
> ```

上面这么写好像没有效果，还是会触发，我把该节点下面的两个button按钮设置type为button，可以倒是可以，不知道会不会有什么别的问题
```ts
toolbar(): (ToolbarItemOptions | CardToolbarItemOptions)[] {
    const items = super.toolbar();
    const colorBtn: any = items.find(item => item.type === 'node' && item.node.hasClass('table-color-dropdown-trigger'))
    colorBtn.node[0].children[0].type = 'button'
    colorBtn.node[0].children[1].type = 'button'
    //   colorBtn.didMount = (node => {
      // node.on('mousedown', e => {
      //   e.preventDefault()
      // })
    // })
    return items.filter(item => item.type !== 'maximize');
  }
```

**Comment by yanmao-cc** [comment]
没别的问题，本身里面的 button 默认没有type

**Comment by yanmao-cc** [comment]
2.8.12 已经默认添加type了
