### ISSUE TITLE
图标字体路径无法配置导致内网使用出现长时间显示异常

### ISSUE THREAD

**Issue by ly01112020** [red-axe/am-editor#124]
1.多次实例化编辑器或多个编辑器，会在当前界面插入N多个 style 标签。
2.字体文件默认cdn路径无法配置（虽然可以覆盖样式）但是会导致离线或内网使用后图标会有一段时间是显示异常的

![image](https://user-images.githubusercontent.com/4043937/161372967-520ce128-5567-4042-8032-3842c8ed6d9f.png)

**Comment by ly01112020** [comment]
1.建议样式标签添加属性进行判重处理
2.字体图标路径是否可以直接内置或做出配置项

**Comment by yanmao-cc** [comment]
多个样式这个html结构截图或复现吗

**Comment by ly01112020** [comment]
解决字体配置项就行了。
我是使用react 封装的编辑器，以数据id作为编辑的id 和组件key 
在一个界面有多个编辑器就发现了生成多个样式，不过这问题不大了。

**Comment by ly01112020** [comment]
配置无效，还是会生成 新的styel 标签并引入默认字体
![image](https://user-images.githubusercontent.com/4043937/162127424-969e77a3-e019-46af-9e91-14e57108be09.png)
![image](https://user-images.githubusercontent.com/4043937/162127500-95c16070-1fa4-4718-85eb-2c92bc905a30.png)
![image](https://user-images.githubusercontent.com/4043937/162127607-425e7ace-b0aa-4cce-8c5f-6c487f0bda4a.png)

**Comment by yanmao-cc** [comment]
你咋配置的呢？你应该把字体文件下载到本地，然后设置他的路径
//at.alicdn.com/t/font_1456030_lnqmc6a6ca.woff2?t=1638071536645
//at.alicdn.com/t/font_1456030_lnqmc6a6ca.woff?t=1638071536645
//at.alicdn.com/t/font_1456030_lnqmc6a6ca.ttf?t=1638071536645

你的css看起来还是旧版本的，2.8.14 上面的css里面已经没有字体样式定义了

**Comment by ly01112020** [comment]
> 你咋配置的呢？你应该把字体文件下载到本地，然后设置他的路径 //at.alicdn.com/t/font_1456030_lnqmc6a6ca.woff2?t=1638071536645 //at.alicdn.com/t/font_1456030_lnqmc6a6ca.woff?t=1638071536645 //at.alicdn.com/t/font_1456030_lnqmc6a6ca.ttf?t=1638071536645
> 
> 你的css看起来还是旧版本的，2.8.14 上面的css里面已经没有字体样式定义了

看我第一张截图，我将你给的参数设置未空字符串，font src 已经为空，说明你写的代码已生效，问题是后续还是插入了默认配置，在我项目中不需要配置这个字体因为我在全局样式中已经引入了。

**Comment by yanmao-cc** [comment]
你的第二张图为什么css里面还有字体定义

**Comment by ly01112020** [comment]
> 

这个 style 标签一看就是编辑器生成的，我默认用的style样式文件，引入本地字体图标。
![image](https://user-images.githubusercontent.com/4043937/162144331-7551d2ba-fb88-4130-aeb6-693ac5e1da6e.png)

**Comment by ly01112020** [comment]
是不是我直接写一个 style id='am-iconfont' 在头部，就不会再生成了，我去试试。

**Comment by yanmao-cc** [comment]
> 是不是我直接写一个 style id='am-iconfont' 在头部，就不会再生成了，我去试试。

是可以，我刚刚加了个 false 选项，设置false就不生成了。

**Comment by ly01112020** [comment]
> 

现在的问题是,还会生成默认样式的 style

**Comment by yanmao-cc** [comment]
默认的style？只会生成有个id的那个标签，其它的不会生成。看起来是不是有多个版本的engine 导致的

**Comment by ly01112020** [comment]
我在 实例化之前 debuuger 中断 我去看 已经生成了，是我使用的姿势不对吗，
![F05C7EEA-AAE7-4e1d-AB60-265F2883F8EF](https://user-images.githubusercontent.com/4043937/162148547-10e952ff-b23b-4ff5-8fef-81c7d90ae428.png)
![94F59859-5FBA-43a8-A176-D28B6CDCF8B9](https://user-images.githubusercontent.com/4043937/162148556-55ec6cbd-2c83-40ff-979e-f3119ba1528c.png)

**Comment by yanmao-cc** [comment]
是不是本地开发缓存之类的？那个css明显不是最新的

**Comment by ly01112020** [comment]
目前只在生成的代码中发现这个，估计和我这边打包策略有关。
![image](https://user-images.githubusercontent.com/4043937/162160767-ac483783-e8b8-451b-8eff-79ee94b9490a.png)
