### ISSUE TITLE
我想在编辑内容里加入禁止编辑区域，有部分在html 里实现吗？

### ISSUE THREAD

**Issue by keepfit123** [red-axe/am-editor#125]

**Comment by yanmao-cc** [comment]
只能用card

**Comment by keepfit123** [comment]
创建一下新标签，包裹限制区域
engineInstance.schema.add({
      name: "limit",
      type: "block",
      attributes: {
        contenteditable: "*",
      },
    });

**Comment by yanmao-cc** [comment]
这个能行吗？没试过
