### ISSUE TITLE
选择区域文本进行“代码“格式化的时候，会删除掉选中的部分代码。这个可以改成选中代码进行格式化的时候，默认填充代码吗

### ISSUE THREAD

**Issue by tankpanv** [red-axe/am-editor#126]
**Is your feature request related to a problem? Please describe.**

选中代码块格式化之后
![image](https://user-images.githubusercontent.com/13927744/161914869-aac4d72a-e778-45ba-b6d9-074728fabe4d.png)

预期选中的代码格式化之后会把选中的代码填充进去
![image](https://user-images.githubusercontent.com/13927744/161915135-76263780-0755-4e6c-9074-0266542f1b07.png)

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.8.15

**Comment by tankpanv** [comment]
> https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.8.15

太好了，最新版本可以了
