### ISSUE TITLE
重写 ImageUploader 方法时异常

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#127]
根据这个[案例](https://editor.aomao.com/zh-CN/config/upload#%E5%8D%95%E4%B8%AA%E6%8F%92%E4%BB%B6%E4%B8%8A%E4%BC%A0)去改写的 ImageUploader 方法，但是在上传的过程中，base64占位图没了，然后进度也是显示 0，等上传成功完成以后能正常显示后端返回的图片路径，想问一下上传过程中的这个问题有什么办法解决吗
![40bdb2ce2bb46c0118fef77079c5db2](https://user-images.githubusercontent.com/40865047/162163879-488c8ce7-8612-4a9a-ab99-b665a4952cec.png)

**Comment by yanmao-cc** [comment]
能提供一个最小可复现的项目看看吗？
或者我想了解下下面的几个问题

1. onReady 方法中的 fileInfo.src 打印出来是什么
2. onUploading 被调用了几次

**Comment by huangyuzai** [comment]
> 能提供一个最小可复现的项目看看吗？ 或者我想了解下下面的几个问题
> 
> 1. onReady 方法中的 fileInfo.src 打印出来是什么
> 2. onUploading 被调用了几次

这个[demo](https://codesandbox.io/s/r8507s?file=/src/Editor/index.tsx)可以复现
![微信截图_20220408104918](https://user-images.githubusercontent.com/40865047/162353422-009c9237-4570-425c-85c8-4586efb1fb88.png)
onReady里面的东西看着好像没啥问题
onUploading只触发了一次

**Comment by yanmao-cc** [comment]
按照这个新的代码试一下吧 https://editor.aomao.com/zh-CN/config/upload

**Comment by huangyuzai** [comment]
好的，解决了，十分感谢

**Comment by byoungd** [comment]
应该的，感谢反馈。





------------------ 原始邮件 ------------------
发件人: huangyuzai ***@***.***&gt;
发送时间: 2022年4月10日 20:04
收件人: red-axe/am-editor ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [red-axe/am-editor] 重写 ImageUploader 方法时异常 (Issue #127)
