### ISSUE TITLE
在工具栏配置code、image、table、codeblock插件没有效果，也没有报错（vue2），大神帮忙看下~

### ISSUE THREAD

**Issue by wakakakk** [red-axe/am-editor#128]
![image](https://user-images.githubusercontent.com/66005999/162610884-6b6160bf-bb2a-4243-b1e2-cce6f78f75e6.png)
![image](https://user-images.githubusercontent.com/66005999/162610928-7feb4852-f3f8-4513-a4c1-93c751a3523a.png)
![image](https://user-images.githubusercontent.com/66005999/162610939-e17f96ed-2534-4033-a2cd-7f7fd4be675d.png)

**Comment by yanmao-cc** [comment]
这个本身默认配置是在collapse 下的，只有自己配置他们的 content 或者icon 和 onClick 事件了

**Comment by wakakakk** [comment]
文档上写着只有type是button和dropdown两种类型下，才有content属性

然后，我直接配置code，好像没有效果，只有在collapse 下才有效果
`{
//不可以
          {
            content: '行内代码',
            name: 'code',
            icon: '<span style="width:23px;height:23px;display: inline-block;border:1px solid #E8E8E8;"><svg t="1649589474069" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="6813" width="200" height="200"><path d="M300.224 224L32 525.76l268.224 301.76 71.776-63.776-211.552-237.984 211.552-237.984zM711.744 224L640 287.776l211.552 237.984L640 763.744l71.744 63.776 268.256-301.76z" p-id="6814"></path></svg><span>'
          }`

**Comment by yanmao-cc** [comment]
{
  type: 'button',
  content: '行内代码',
  onClick: () => {
   console.log('行内代码 click')
  }
}

**Comment by wakakakk** [comment]
请问编辑器和阅读器的大纲怎么配置

**Comment by wakakakk** [comment]
工具栏可以自定义设置末尾插入行和起始插入行的功能吗

**Comment by yanmao-cc** [comment]
> 请问编辑器和阅读器的大纲怎么配置

可以获取到大纲数据  https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java ，然后自己渲染

**Comment by yanmao-cc** [comment]
> 工具栏可以自定义设置末尾插入行和起始插入行的功能吗

工具栏只是提供ui，你可以配置一个按钮，onClick 的时候调用 engine api

**Comment by wakakakk** [comment]
> > 请问编辑器和阅读器的大纲怎么配置
> 
> 可以获取到大纲数据 https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java ，然后自己渲染

这个要怎么用呀，建议增加一个可配置大纲的功能哦(●'◡'●)

**Comment by wakakakk** [comment]
> > > 请问编辑器和阅读器的大纲怎么配置
> > 
> > 
> > 可以获取到大纲数据 https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java ，然后自己渲染
> 
> 这个要怎么用呀，建议增加一个可配置大纲的功能哦(●'◡'●)

或者有没有使用大纲的源码参考下

**Comment by yanmao-cc** [comment]
我发错了链接。。。https://editor.aomao.com/zh-CN/plugin/plugin-heading#%E5%A4%A7%E7%BA%B2 这个才对

**Comment by yanmao-cc** [comment]
另外还有个 react 例子就是 editor.aomao.com 上面的例子 https://github.com/red-axe/am-editor/tree/master/examples/react/components/toc

**Comment by wakakakk** [comment]
> 我发错了链接。。。https://editor.aomao.com/zh-CN/plugin/plugin-heading#%E5%A4%A7%E7%BA%B2 这个才对

好的哦 谢啦

**Comment by wakakakk** [comment]
> 另外还有个 react 例子就是 editor.aomao.com 上面的例子 https://github.com/red-axe/am-editor/tree/master/examples/react/components/toc

有没有vue2的例子呀？react看不懂，太菜了==
