### ISSUE TITLE
粘贴表格后，表格内的单元格中文本首位有p标签换行？

### ISSUE THREAD

**Issue by attraction11** [red-axe/am-editor#129]
**Describe the bug**
大佬，在使用编辑器时，表格内单元格首尾换行了，比较占位置，也清不掉。

**Additional context**

**Comment by yanmao-cc** [comment]
怎么复现

**Comment by attraction11** [comment]
将Word 文档中的表格复制，粘贴到编辑器中就可以复现。 和Word 文档中不同，编辑器中的表格，每个单元格内上下都有空行。

**Comment by yanmao-cc** [comment]
@aomao/plugin-table: 2.8.21
其它插件和engine 升级到 2.8.20 就可以了
