### ISSUE TITLE
编辑和预览模式支持分页视图

### ISSUE THREAD

**Issue by amibug** [red-axe/am-editor#130]
文档有排版和打印的用途，编辑器和预览界面如何支持分页视图

**Comment by yanmao-cc** [comment]
分页暂时没有解决方案

**Comment by yanmao-cc** [comment]
高度宽度自己修改外面容器的样式就好了

**Comment by amibug** [comment]
word分页视图有支持计划吗？

**Comment by yanmao-cc** [comment]
下一个自绘光标的版本会支持

**Comment by amibug** [comment]
交互形式供参考

![image](https://user-images.githubusercontent.com/1797385/163089710-c1fb0f2b-9e4d-45fc-9d23-572a0fbf0705.png)
