### ISSUE TITLE
css污染问题

### ISSUE THREAD

**Issue by xuxinyuancode** [red-axe/am-editor#133]
写入代码`require("am-editor-toolbar-vue2")`后会全局污染css，有什么好的结局办法吗？

**Comment by yanmao-cc** [comment]
是 ant-design-vue 和 elementui 样式冲突了吗

**Comment by xuxinyuancode** [comment]
差不多是这个意思，我用的tailwindcss，然后ant-design-vue会有一个全局css，最终会覆盖我的tailwindcss，目前并没有找到一个很好的解决办法。

**Comment by yanmao-cc** [comment]
没有好的解决办法，只能看多不多，外围进行样式覆盖

**Comment by xuxinyuancode** [comment]
还有一个重要的问题是，这个是在mounted里面加载的，想要覆盖还需要在加载完成之后再去加载覆盖文件

**Comment by yanmao-cc** [comment]
可以使用 !important 或者限定css名称
