### ISSUE TITLE
@aomao/plugin-alignment 插件设置左对齐失效

### ISSUE THREAD

**Issue by amibug** [red-axe/am-editor#134]
**Describe the bug**
@aomao/plugin-alignment 插件设置左对齐失效

@aomao/engine: '2.8.15'
@aomao/plugin-alignment: '2.8.15'

**To Reproduce**
https://user-images.githubusercontent.com/1797385/162989307-12cea82d-cd5b-46d5-ae00-3099a8c8d3b5.mov

**Comment by yanmao-cc** [comment]
应该是外围样式设置了 text-align: center 吧，删掉即可

**Comment by amibug** [comment]
fixed
