### ISSUE TITLE
@aomao/plugin-image执行插入图片后如何获取卡片id

### ISSUE THREAD

**Issue by Qujh97** [red-axe/am-editor#135]
我在富文本中新建自定义的流程图插件，绘图完成后利用image插件插入图片，但是需要保存流程图插件生成的JSON方便后续编辑，期望插入卡片时能获取节点id根据id保存JSON。

如`const id = engine.command.execute(Image.pluginName, 'done', '图片地址');`

**Comment by yanmao-cc** [comment]
可以继承 Image 插件，然后重写 execute 方法

```ts
execute(
		status: 'uploading' | 'done' | 'error',
		src: string,
		alt?: string,
	): void {
		const value: ImageValue = {
			status,
			src,
			alt,
		};
		if (status === 'error') {
			value.src = '';
			value.message = src;
		}
		this.editor.card.insert('image', value);
	}
```

**Comment by csh159** [comment]
问一下图片上怎么添加一个关闭按钮？

**Comment by big-camel** [comment]
> 问一下图片上怎么添加一个关闭按钮？
继承 ImageComponent 类，重写 toolbar 方法

**Comment by csh159** [comment]
> > 问一下图片上怎么添加一个关闭按钮？
> > 继承 ImageComponent 类，重写 toolbar 方法
我想在图片右上角添加个关闭按钮，怎么给监听事件？

**Comment by csh159** [comment]
问下怎么更换图片地址，比如已经添加了一张图片，然后会对图片进行编辑后怎么修改当前的图片？

**Comment by Qujh97** [comment]
> 问下怎么更换图片地址，比如已经添加了一张图片，然后会对图片进行编辑后怎么修改当前的图片？

删掉重新上传本身就实现了编辑，为什么要单独给图片加个编辑功能，你见过word里的图片有编辑功能吗

**Comment by csh159** [comment]
> > 问下怎么更换图片地址，比如已经添加了一张图片，然后会对图片进行编辑后怎么修改当前的图片？
> 
> 删掉重新上传本身就实现了编辑，为什么要单独给图片加个编辑功能，你见过word里的图片有编辑功能吗

我需要做到手机上，手机上可以对图片编辑

**Comment by big-camel** [comment]
在 ImageComponent 内可以调用 this.setValue({url: ''}) 修改卡片的图片地址，如果修改img的，正常操作document也行

**Comment by csh159** [comment]
在不，问一下焦点变化之后再次设置文字等样式无效，还是上一次的样式。比如首次设置好了样式，然后点击手机其他控件，在点击编辑器设置样式就无效了！
