### ISSUE TITLE
打包产物过大

### ISSUE THREAD

**Issue by ly01112020** [red-axe/am-editor#139]
包的尺寸还有优化空间吗
![image](https://user-images.githubusercontent.com/4043937/163502000-d4cd5136-d2b5-4086-9ba1-c3ad13d21e45.png)
![image](https://user-images.githubusercontent.com/4043937/163502092-493496cd-2c1d-4a43-ac50-7f953d3b18dc.png)

**Comment by ly01112020** [comment]
经分析，打包产物有很多重复代码

**Comment by ly01112020** [comment]
例如
![image](https://user-images.githubusercontent.com/4043937/163504243-3f534a83-ad05-4f0f-b4d7-44aa72452f6f.png)

**Comment by yanmao-cc** [comment]
看起来你是不是有多个版本的 engine

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/163504538-217e83a7-1242-487f-900b-7e759bbbf80d.png)

**Comment by ly01112020** [comment]
多个版本的 engine ？？，一直是 npm install 的 刚才删掉 重新装还是这个问题，
插件包版本和engine不一致会有问题吗？

**Comment by ly01112020** [comment]
多个版本的 engine ？？，一直是 npm install 的 刚才删掉 重新装还是这个问题，
插件包版本和engine不一致会有问题吗？

**Comment by yanmao-cc** [comment]
是的，有没有可能你的插件版本是2.7的，依赖的是 2.7的engine，但是安装的 engine是2.8的？

**Comment by ly01112020** [comment]
全部改成 2.8.15 还是一样的，就算有多个engine 也不应该重复这么多

**Comment by yanmao-cc** [comment]
就是打包器给你重复打包了呗

**Comment by ly01112020** [comment]
我其他插件都没问题

**Comment by yanmao-cc** [comment]
一个简单的办法 node_modules/@aomao/plugin-xx/node_modules 看看有没有 @aomao/engine 目录

**Comment by ly01112020** [comment]
![image](https://user-images.githubusercontent.com/4043937/163510484-feb0fd54-bbb0-4119-a327-237071fe1a65.png)
![image](https://user-images.githubusercontent.com/4043937/163510489-ae044aed-0f43-4aee-a2a2-d65290324839.png)
确实有，但是这两个版本是一样的

**Comment by yanmao-cc** [comment]
正常情况下，插件下没有 @aomao ，看看这是为啥呢，不是 lock造成的

**Comment by ly01112020** [comment]
你的插件开发 是不是应该将 engine 放在 
![image](https://user-images.githubusercontent.com/4043937/163510776-6b1e7809-f950-4758-8324-a7020d9ccc86.png)
这里

**Comment by ly01112020** [comment]
而且我还不能用你高版本的 engine 因为有一个bug导致我自定义的组件插入顺序有问题没更新

**Comment by yanmao-cc** [comment]
啥bug发过来修一下

**Comment by ly01112020** [comment]
是lock.jsoon 导致的，中途指定了 engine 版本来测试问题
