### ISSUE TITLE
可否出一个vue2自定义插件的教程，示例的看的不是特别懂！

### ISSUE THREAD

**Issue by wangmingadmin** [red-axe/am-editor#140]

**Comment by yanmao-cc** [comment]
https://github.com/zb201307/am-editor-vue2/tree/main/packages

**Comment by wangmingadmin** [comment]
还有一个问题，就是能否把公式插件转换成本地转换的，我们项目实在离线环境运行的！

**Comment by yanmao-cc** [comment]
你可以使用card机制和可以生成公式的代码库做一个 https://github.com/mathjax/MathJax-demos-web

**Comment by wangmingadmin** [comment]
好的
