### ISSUE TITLE
2.8.10 版本后 <cursor/>位置不正确

### ISSUE THREAD

**Issue by ly01112020** [red-axe/am-editor#142]
如题
![image](https://user-images.githubusercontent.com/4043937/163516432-c569baf6-70c8-4d79-a2ed-6f1b78fe8248.png)
![image](https://user-images.githubusercontent.com/4043937/163516439-7e22a802-3e17-46c9-9064-5e38d7abda5c.png)

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/163516671-450a536e-447c-4d19-9d07-f5587a24b926.png)
我本地最新的没复现，是不是修复了？

**Comment by ly01112020** [comment]
你什么版本

**Comment by yanmao-cc** [comment]
2.8.18


from 阿里邮箱HD iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年04月15日 12:09:21
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 2.8.10 版本后 <cursor/>位置不正确 (Issue #142)

你什么版本

**Comment by ly01112020** [comment]
默认安装现在最新不是 17吗，版本更新的这么快

**Comment by yanmao-cc** [comment]
刚发的，17我也没遇到这个问题呀。你是不是按钮点击的时候光标丢失了


from 阿里邮箱HD iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年04月15日 12:11:09
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 2.8.10 版本后 <cursor/>位置不正确 (Issue #142)

默认安装现在最新不是 17吗，版本更新的这么快

**Comment by ly01112020** [comment]
我在编辑器之外点击保存或插入内容光标肯定会丢啊，

**Comment by yanmao-cc** [comment]
mousedown e.preventDefault 阻止默认行为就好了


from 阿里邮箱HD iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年04月15日 12:15:21
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 2.8.10 版本后 <cursor/>位置不正确 (Issue #142)

我在编辑器之外点击保存或插入内容光标肯定会丢啊，

**Comment by ly01112020** [comment]
不行，我右侧设计有展开和搜索功能，不能每个都加 (阻止默认行为，总有不可预期的)
我在搜索内容后 将内容插入富文本，.10版本的<cursor/> 位置是ok的，实在不行我只能退回版本，目前未找是什么原因造成的

现在的版本不是插入到顶部就是在尾部

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.8.19
