### ISSUE TITLE
plugin-image 更新 2.8.18 后，阅读模式异常

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#143]
plugin-image 更新到 2.8.18 后，在阅读模式下，图片可以放大预览，但是有多余的元素
![企业微信截图_16500066436983](https://user-images.githubusercontent.com/40865047/163537825-b848e193-99aa-49f9-9a1f-78dcb333df9b.png)

**Comment by yanmao-cc** [comment]
这个是你 getValue 获取到的值再给 View 的吗？

**Comment by huangyuzai** [comment]
是先上传图片以后，把编辑器里面的内容发到后台，显示的时候拿内容数据用  engine.setValue()  写进去的

**Comment by yanmao-cc** [comment]
编辑器的内容发出来看一下，是使用getValue获取的值吗？

**Comment by huangyuzai** [comment]
哦对，是的，用getValue()获取的值，图片可能预览不了，现在图片是内网的。
编辑器内容：  
  <p data-id=\"pd157317-cCN2VpDn\">测试计划11</p><p data-id=\"pd157317-U0E9lNTb\"><card type=\"inline\" name=\"image\" editable=\"false\" value=\"data:%7B%22status%22%3A%22done%22%2C%22size%22%3A%7B%22width%22%3A433%2C%22height%22%3A157%2C%22naturalHeight%22%3A157%2C%22naturalWidth%22%3A433%7D%2C%22id%22%3A%22fmlqM%22%2C%22type%22%3A%22inline%22%2C%22percent%22%3A100%2C%22src%22%3A%22http%3A%2F%2F192.168.30.25%3A9999%2Fadmin%2Fsys-file%2Fqq-forum-1302557883%2Foa%2F6052196fb2f64c2f85c808da582cf49a.png%22%7D\"></card></p>

**Comment by yanmao-cc** [comment]
测试计划11 ?? 不是一段html吗？

**Comment by huangyuzai** [comment]
```
<p data-id=\"pd157317-cCN2VpDn\">测试计划11</p><p data-id=\"pd157317-U0E9lNTb\"><card type=\"inline\" name=\"image\" editable=\"false\" value=\"data:%7B%22status%22%3A%22done%22%2C%22size%22%3A%7B%22width%22%3A433%2C%22height%22%3A157%2C%22naturalHeight%22%3A157%2C%22naturalWidth%22%3A433%7D%2C%22id%22%3A%22fmlqM%22%2C%22type%22%3A%22inline%22%2C%22percent%22%3A100%2C%22src%22%3A%22http%3A%2F%2F192.168.30.25%3A9999%2Fadmin%2Fsys-file%2Fqq-forum-1302557883%2Foa%2F6052196fb2f64c2f85c808da582cf49a.png%22%7D\"></card></p>
```

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/163540202-21e63c63-7014-4a34-a3ae-03d6b633cb8e.png)
复现不了

**Comment by huangyuzai** [comment]
对，是的，我上传之前拖动了图片大小

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.8.19
