### ISSUE TITLE
setHtml() 方法会丢失文字的样式

### ISSUE THREAD

**Issue by number317** [red-axe/am-editor#144]
**Describe the bug**
已经设置好的文字样式用 getHtml 导出后，再用 setHtml 设置回去会发生样式丢失

**To Reproduce**
导出的样式
![image](https://user-images.githubusercontent.com/15346773/163801677-8f01b61a-987c-43b3-b310-493c05b75af4.png)
导入后的样式
![image](https://user-images.githubusercontent.com/15346773/163801809-8c349300-8d2d-487e-95cc-eb7f52db997e.png)
可以看到文字大小，字体的样式发生了丢失

大佬有空帮忙看看

**Comment by yanmao-cc** [comment]
无法复现，提供一下复现的方法
```html
<div data-element="root" class="am-engine"><p data-id="p838747a-t6eGt8V1"><span style="font-size: 19px;">19</span></p><p data-id="p838747a-E1ja5vOi"><span style="font-size: 24px;"><span style="color: #f5222d;">24</span></span></p><p data-id="p838747a-7T7rSPsz"><span style="font-family: STSong, 华文宋体, SimSun, &quot;Songti SC&quot;, NSimSun, serif;">宋体</span></p></div>
```

**Comment by number317** [comment]
大佬我搞了个 demo 来复现
[am-editor.zip](https://github.com/red-axe/am-editor/files/8506016/am-editor.zip)
下载后
`npm install && npm run dev`
访问 localhost:3000
给文字设置字体大小 24px
![image](https://user-images.githubusercontent.com/15346773/163818247-b1e023be-7980-4a0e-a5b3-f82817aac7e5.png)
点击 save，会将 getHtml() 的值暂存
![image](https://user-images.githubusercontent.com/15346773/163818604-07671d54-6f4f-4efc-aef8-edbda9b784c7.png)
点击 clear，清空编辑器
![image](https://user-images.githubusercontent.com/15346773/163818717-ea5ce6e5-f273-47f6-88ad-75bbf9305ca5.png)
点击 restore，将暂存的值通过 setHtml 重新赋值给编辑器，但发现字体大小样式丢失
![image](https://user-images.githubusercontent.com/15346773/163818763-7651cbd5-7845-4053-9747-0e137431266d.png)

**Comment by yanmao-cc** [comment]
默认被过滤掉了 https://editor.aomao.com/zh-CN/plugin/plugin-fontsize#%E7%B2%98%E8%B4%B4%E8%BF%87%E6%BB%A4%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AD%97%E4%BD%93%E5%A4%A7%E5%B0%8F 可以看看这里的配置

字体同样的道理

```ts
//实例化引擎
const engine = new Engine(ref.current, {
    plugins: [ToolbarPlugin, FontSize, Bold],
    config:{
      [FontSize.pluginName]: {
        //Configure the font size to be filtered after pasting
        filter: (fontSize) => {
            return ["12px","13px","14px","15px","16px","19px","22px","24px","29px","32px","40px","48px"] .indexOf(fontSize)> -1
        }
      }
  }
});
```

**Comment by number317** [comment]
原来是这样，感谢大佬，请大佬喝咖啡☕
