### ISSUE TITLE
表格组件中插入自定义组件（有状态组件），组件的值丢失

### ISSUE THREAD

**Issue by ly01112020** [red-axe/am-editor#147]
![image](https://user-images.githubusercontent.com/4043937/163974644-274959f8-d52b-4a00-91bf-3f3b6b3afa00.png)
![image](https://user-images.githubusercontent.com/4043937/163975962-b510a85c-911c-4fa5-8a99-2a40ed9de88b.png)
如图，没找到，刷新界面后加载数据，脑暴弹框内容为空

**Comment by yanmao-cc** [comment]
那你脑暴弹框的内容保存到卡片的value 里面了吗？能给个最小复现demo吗

**Comment by ly01112020** [comment]
直接在编辑器里是 ok 的，但是新的问题又来了，为了用户方便找到光标，这个组件是  INLINE 模式，但是内部用 table 布局
再次渲染会将里面的文字单独渲染出来，使用block模式则正常
![image](https://user-images.githubusercontent.com/4043937/163977550-37dfea21-79ac-4928-a6eb-6d4bb5a1467f.png)

**Comment by ly01112020** [comment]
云内隔离开发，好麻烦的，如果你不好复现，回头我在外面写一下子

**Comment by yanmao-cc** [comment]
你的头脑风暴卡片是inline类型的可编辑卡片还是普通卡片？

**Comment by ly01112020** [comment]
现在是 inline 类型 可编辑（只是input输入那部分可编辑）

**Comment by yanmao-cc** [comment]
不是卡片 [contenteditable](https://editor.aomao.com/zh-CN/plugin/tutorials-card#contenteditable) 的这个属性设置的吧？这个属性不能用于inline类型的卡片

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.8.26
