### ISSUE TITLE
代码块在查看模式无法单独复制某一行

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#148]
**Describe the bug**
发现代码块在查看模式无法单行复制，有没有可以通过配置解决

**Comment by yanmao-cc** [comment]
@aomao/plugin-codeblock 2.8.25

**Comment by chunyangyang** [comment]
你好，复制可以了，但是在我的业务中有个奇怪的现象，麻烦给看下原因；

我的业务是默认进来是不可以编辑状态，后期可以通过点击按钮切换，

问题：
1.默认进来的时候是可以复制，但是头部的自动换行和全局复制没有出现。如下图
![image](https://user-images.githubusercontent.com/20843521/164392995-97b31134-da64-4373-9352-775398983124.png)

2.在第一个问题的基础上点击切换成编辑模式，代码块无法输入，需要在选择一段代码后，才可以正常输入内容。如下图
![image](https://user-images.githubusercontent.com/20843521/164394015-08b9f442-5dac-48a1-80e3-f13231557fe5.png)

![image](https://user-images.githubusercontent.com/20843521/164393384-f036ddb8-fc40-4d82-a275-783793f9e2d2.png)

3.最后在打开编辑的模式下，我切换两个编辑文档后一切功能就正常了。如下图
![image](https://user-images.githubusercontent.com/20843521/164394434-c5e97e4a-8ee3-4506-a4a5-32f156348630.png)

**Comment by yanmao-cc** [comment]
@chunyangyang 第二个问题未复现，是vue还是 react ？

**Comment by yanmao-cc** [comment]
@chunyangyang 第二个问题未复现，是 react 还是 vue ？

**Comment by chunyangyang** [comment]
是react
你可以把examples里面的只读和编辑两个按钮房出来，然后切换到只读，刷新页面就可以看到问题了，如下图：
![image](https://user-images.githubusercontent.com/20843521/164413404-1bceef64-ddbb-4552-96ae-b3b086c434d7.png)

**Comment by yanmao-cc** [comment]
嗯，但是再切换到可编辑没有复现不能输入问题

**Comment by chunyangyang** [comment]
我也搞不懂了，我再也一份就可以了，和复制过来有原因吗
![image](https://user-images.githubusercontent.com/20843521/164419830-b5c72900-2eec-40f9-9b4d-4af77fefaecc.png)
![image](https://user-images.githubusercontent.com/20843521/164419922-b60b8671-ca21-4fdd-ae8b-801255eba6b7.png)

**Comment by yanmao-cc** [comment]
之前修的显示工具栏，可能连带一起修好了吧

**Comment by chunyangyang** [comment]
嗯 我也这样想不然又点奇怪，显示工具已经改了吗？

**Comment by yanmao-cc** [comment]
是的

**Comment by chunyangyang** [comment]
好，我去看下，谢谢了

**Comment by yanmao-cc** [comment]
还没发布

**Comment by chunyangyang** [comment]
你好，预计什么时候发布
