### ISSUE TITLE
工具栏的上传图片没有效果

### ISSUE THREAD

**Issue by wakakakk** [red-axe/am-editor#152]
我在vue2中这样配置上传图片功能，但是没有效果，是不是配置错了啊
![image](https://user-images.githubusercontent.com/66005999/165468285-994f7f8c-9883-4b6a-831b-9a346d6b41d6.png)

**Comment by wakakakk** [comment]
> 是 image-uploader ，[ImageUploader.pluginName] 也行

![image](https://user-images.githubusercontent.com/66005999/165661095-7aa57016-b822-4b66-a35b-d36330396aed.png)
我这样简单的配置后，工具栏的上传还是禁选的状态

**Comment by wakakakk** [comment]
> 是 image-uploader ，[ImageUploader.pluginName] 也行

![image](https://user-images.githubusercontent.com/66005999/165661209-54074599-683d-4edd-b545-491952a5f309.png)
![image](https://user-images.githubusercontent.com/66005999/165661255-737bfd5c-ae5b-4e35-b366-3970ff4bae3c.png)
我这样简单配置后，工具栏还是禁选的状态

**Comment by yanmao-cc** [comment]
你是没有把 ImageUploader 配置到 plugins 里面吧

**Comment by wakakakk** [comment]
> 你是没有把 ImageUploader 配置到 plugins 里面吧

![image](https://user-images.githubusercontent.com/66005999/165755995-3734a7c9-20d2-49cd-8c14-d6bd32192524.png)
有啊

**Comment by yanmao-cc** [comment]
按钮配置 name: image-uploader 工具栏会检测引擎中是否配置对应 name 的插件。如果未插件会直接禁用。
或者再配置一下按钮的 onDisabled 方法 https://editor.aomao.com/zh-CN/config/toolbar#ondisabled ，自定义禁用逻辑
