### ISSUE TITLE
如何获取markdown原信息

### ISSUE THREAD

**Issue by chenxiaobin** [red-axe/am-editor#156]
希望能够暴露获取markdown原始字符串的方法
我们的场景是：
新产品升级考虑使用你的编辑器，但是有些老平台还在用旧的编辑器，旧的编辑器是直接用markdown渲染的，希望二者能兼容

**Comment by yanmao-cc** [comment]
本身编辑器没有获取markdown语法的api，转换markdown也只是针对部分markdown语法检测转换的
