### ISSUE TITLE
在查看模式下表格可以使用ctr+v粘贴进数据

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#158]
1.在编辑完表格后复制表格内容，切换到查看模式使用键盘ctr+v可以往表格里面写入内容。如下图：
![image](https://user-images.githubusercontent.com/20843521/168230981-f0ae922f-0c77-45d6-b3d1-f0ad91f6d965.png)

期望在查看模式不能粘贴进入内容

**Comment by yanmao-cc** [comment]
@aomao/plugin-table@2.9.1
