### ISSUE TITLE
配置项可不可以动态设置？

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#159]
我看文档说这个配置项是需要在引擎实例化时传入，想问问支不支持动态设置
![image](https://user-images.githubusercontent.com/40865047/168231736-6e46cc43-0e5a-4ec8-860b-6335ca4ed536.png)

比如 readonly 这个属性，在实例化的时候设置为 false，后面只需要根据某些值去动态更改状态而不需要再次实例化引擎

**Comment by yanmao-cc** [comment]
不能动态设置。但是readonly 可以通过 engine.readonly 去设置修改
