### ISSUE TITLE
Table左上角拖拽键无效

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#162]
Table左上角拖拽键无效

希望可以看看能不能修复这个问题
![截屏2022-05-15 22 36 34](https://user-images.githubusercontent.com/35056286/168478404-ff3f6ee4-c118-49f5-8c19-8cef38635b84.png)

**Comment by yanmao-cc** [comment]
什么版本，无法复现

**Comment by BOKE2014** [comment]
> 什么版本，无法复现
[editor.aomao.com](https://editor.aomao.com/)

**Comment by yanmao-cc** [comment]
我这里无法复现

**Comment by BOKE2014** [comment]
> 我这里无法复现

好吧：（，Mac Chrome是无法拖动的，Edge略好

**Comment by yanmao-cc** [comment]
macOs Monterry
