### ISSUE TITLE
表格的放大功能是否可以做成配置化

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#163]
在有些业务场景表格不允许放大，目前没有办法可以配置这个工具条。如下图：
![image](https://user-images.githubusercontent.com/20843521/168504839-6f57bd70-692e-4ec2-ac77-91b48ed5c8d7.png)
期望可以配置这个工具条，对放大可以隐藏起来，效果如下图：
![image](https://user-images.githubusercontent.com/20843521/168504969-050eb5b9-a7c0-4b9c-8ece-80e4d2d17a29.png)

**Comment by yanmao-cc** [comment]
可以先临时继承 TableComponent 然后 重写 toolbar() 方法，最后过滤掉 return super.toolbar().filter(item => item.type !== 'maximize')

**Comment by chunyangyang** [comment]
目前是这样处理的，只是期望组件这边可以支持更好

**Comment by yanmao-cc** [comment]
2.9.1 版本支持了 https://editor.aomao.com/zh-CN/docs/faq#%E5%A6%82%E4%BD%95%E5%AE%9A%E5%88%B6%E5%8D%A1%E7%89%87%E5%B7%A5%E5%85%B7%E6%A0%8F

**Comment by chunyangyang** [comment]
好的，辛苦
