### ISSUE TITLE
如何自定义popup的工具按钮

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#164]
你好，作者，请问如何在ToolbarPlugin下面的popup自定义一个自己的弹窗组件

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/config/toolbar#%E5%BC%B9%E5%87%BA%E6%A1%86

**Comment by smallCF** [comment]
感谢，刚刚已经找到，写出来了

**Comment by smallCF** [comment]
还有一个疑问，就是自己写的popup，如何执行onclick后隐藏popup弹窗呢，我看hide没有找到

**Comment by yanmao-cc** [comment]
这个就根据 range 判断的，onclick 你就监听document的click事件呗，没点击到编辑区域就给隐藏不就行了
