### ISSUE TITLE
光标位置不对和光标消失的问题

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#165]
1、移动端（android）微信打开网页，任务列表输入后光标停留在倒数第二个字后面（光标应该停留在最后一个字的后面）。
android其他的浏览器，如：chrome，edge等没有此问题。

2、iOS和iPad OS通过微信使用没有发现问题，但chrome浏览器任务列表输入后回车光标消失（光标不应该消失）。

**Comment by yanmao-cc** [comment]
2. iOS chrome浏览器 未复现
