### ISSUE TITLE
链接地址操作有序无序的切换，数据行会被删除，如视频所示

### ISSUE THREAD

**Issue by Rock-liyi** [red-axe/am-editor#167]
**Describe the bug**
如视频所示
https://user-images.githubusercontent.com/35133768/169443407-c82df79a-26ce-4104-800a-3a197168a4b8.mp4

-   OS: [e.g. windows]
-   Browser [e.g. chrome]
-   Version [e.g. 2.0.9]

**Comment by yanmao-cc** [comment]
视频里面看起来那段无序列表结构不在正确的位置，不知道如何复现这段无序列表。光标为题解决了

**Comment by Rock-liyi** [comment]
> 视频里面看起来那段无序列表结构不在正确的位置，不知道如何复现这段无序列表。光标为题解决了

光标的问题，需要升级那个组件？

**Comment by yanmao-cc** [comment]
2.9.1 光标问题。视频上的需要更多的复现步骤
