### ISSUE TITLE
复制粘贴会粘贴两段重复的内容

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#168]
从别的地方复制内容到编辑器时，回填的时候会粘贴两段相同的内容
例如：复制   test，粘贴到编辑器就会变成  testest  

这个简单 [demo](https://codesandbox.io/s/silent-haze-fu534d?file=/src/Editor/index.tsx) 可以复现

**Comment by yanmao-cc** [comment]
不知道为什么你的 new Engine 执行了两次，你应该在 useEffect 中加入

```ts
return () => {
   _engine.destroy()
}
```
在组件卸载的时候注销engine
