### ISSUE TITLE
手动调用 engine.blur() 事件时能否设置 toolbar 为不可用状态

### ISSUE THREAD

**Issue by huangyuzai** [red-axe/am-editor#169]
多个编辑器实例的情况下，设置了内容回显并调用 engine.blur() 事件，但是工具栏还是可以操作的，所以就会导致点击第一个编辑器实例的工具栏按钮，相关内容会添加到最后一个编辑器里面
![image](https://user-images.githubusercontent.com/40865047/169735501-853cc2f2-3ac2-47af-938f-db85e8ef8ed8.png)

**Comment by yanmao-cc** [comment]
2.9.2 版本修了
