### ISSUE TITLE
光标不渲染

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#170]
作者你好，我想请问一下，就是跑am-editor-vue是有光标的，但是自己另起一个项目加入，member里面有我的对象了，无法渲染对于的光标，这是需要作什么处理吗？

**Comment by smallCF** [comment]
找到了，麻烦您了

**Comment by daidaic** [comment]
你好 问下怎么解决的 现在有同样问题

**Comment by smallCF** [comment]
我这边是之前没有进行广播




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "red-axe/am-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午2:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [red-axe/am-editor] 光标不渲染 (Issue #170)





 
你好 问下怎么解决的 现在有同样问题

**Comment by daidaic** [comment]
好的 谢谢 请问下 你记得和那个函数有关吗

**Comment by smallCF** [comment]
没有理解你说的是什么函数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "red-axe/am-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午2:02
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [red-axe/am-editor] 光标不渲染 (Issue #170)





 
好的 谢谢 请问下 你记得和那个函数有关吗
