### ISSUE TITLE
一个关于视频播放的问题

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#171]
我的视频上传是采用了断点续传，在上传成功后播放可以正常，但是无法拖动播放，也就是无法快进播放，不知大佬是否知道原因，或者有时间给提供点排查思路吗
如下图：
![image](https://user-images.githubusercontent.com/20843521/170209592-eb6125e0-9e92-40b9-b9ce-4998b01cd233.png)

**Comment by yanmao-cc** [comment]
因为外面有个遮罩层吗？

**Comment by chunyangyang** [comment]
遮罩层我已经隐藏了，不知道是不是后端视频链接的问题
![image](https://user-images.githubusercontent.com/20843521/170407611-2f67e68e-3959-436c-a787-b249a733598d.png)
![image](https://user-images.githubusercontent.com/20843521/170407660-64d17904-e085-4651-a3ac-3791cc13566a.png)
