### ISSUE TITLE
一个关于Comments的问题

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#173]
目前的comments是所有用户都可以彼此编辑和删除的，能不能把编辑和删除限定于写comments的个人，即：只能删除和修改自己的，别人的只能看不能修改和删除？

谢谢！

**Comment by yanmao-cc** [comment]
这只是在编辑器外的一个react组件，为什么不自己调整一下呢？

**Comment by yanmao-cc** [comment]
这只是在编辑器外的一个react组件，为什么不自己调整一下呢？

------------------------------------------------------------------
***@***.***>
日　期：2022年05月26日 12:09:57
***@***.***>
***@***.***>
主　题：[red-axe/am-editor] 一个关于Comments的问题 (Issue #173)

目前的comments是所有用户都可以彼此编辑和删除的，能不能把编辑和删除限定于写comments的个人，即：只能删除和修改自己的，别人的只能看不能修改和删除？
谢谢！
