### ISSUE TITLE
作者,这是语雀的开源先行版吗?看很多功能和语雀一模一样问一下

### ISSUE THREAD

**Issue by jiangzhaojie22** [red-axe/am-editor#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yanmao-cc** [comment]
不是的哦~

**Comment by jiangzhaojie22** [comment]
> 不是的哦~

soga,那这个项目和语雀的关系是怎样的呢大佬?

**Comment by yanmao-cc** [comment]
没有关系，有些模仿
