### ISSUE TITLE
发现一个编辑页面和阅读界面不同步的问题

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#177]
编辑界面
![截屏2022-05-27 12 01 40](https://user-images.githubusercontent.com/35056286/170627032-340874fe-306d-4f71-a2e2-18db1943713a.png)
阅读界面
![截屏2022-05-27 12 01 57](https://user-images.githubusercontent.com/35056286/170627186-d3cbabbe-18be-43e7-acf0-de983aec0fef.png)

**Comment by yanmao-cc** [comment]
因为这是用于测试的，我本地也是用的这个线上服务，保存后，阅读界面直接读取的服务器上的数据

**Comment by BOKE2014** [comment]
> 因为这是用于测试的，我本地也是用的这个线上服务，保存后，阅读界面直接读取的服务器上的数据

前几天和昨天没有发现这个问题：（

**Comment by yanmao-cc** [comment]
因为我刚刚本地测试保存了数据，所以你刚好看到。这种问题数据源都需要自定义的，与编辑器无关。
