### ISSUE TITLE
有两个问题反馈作者

### ISSUE THREAD

**Issue by BOKE2014** [red-axe/am-editor#179]
1、华为安卓手机使用chrome浏览器能够接收和看到其他人对文件的编辑，但是在安卓chrome上打字等操作在其他设备上无法收到（其他设备上可以看到光标在动），iOS，iPad OS，macOS和windows上的chrome都没有问题。是不是chrome版本太低？（华为不给更新）

2、iPad 上各个浏览器界面都没有自适应？Safari可以看到大纲和添加Comments，其他的浏览器，如：chrome和edge可以左右拉动看不到大纲也写不了comments（选中文字也不显示comments窗口）

**Comment by yanmao-cc** [comment]
2. 这个这是演示网站，没有做那么多适配

**Comment by yanmao-cc** [comment]
[#](https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.9.10)

**Comment by BOKE2014** [comment]
👌

**Comment by BOKE2014** [comment]
> https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.9.10

通报作者，这个确实可以解决低版本的问题，但是引发另外一个问题，就是屏幕闪动，移动端和PC端都有闪动：（

**Comment by yanmao-cc** [comment]
什么是闪动

**Comment by BOKE2014** [comment]
> 什么是闪动

就是感觉延迟比较大，然后界面一闪一闪的就像是在快速的刷新界面，移动端的界面和PC端的界面都在闪

**Comment by BOKE2014** [comment]
> 什么是闪动

所有的浏览器都闪

**Comment by BOKE2014** [comment]
牛
