### ISSUE TITLE
safari下卡顿

### ISSUE THREAD

**Issue by rustbomber** [red-axe/am-editor#182]
**Describe the bug**

在safari下，只要内容稍微一多，则会出现输入文字延迟，光标定位延迟情况，特别是在表格较多的情况下。

**To Reproduce**

随便插入一些图片，表格、文字就出现卡顿情况，见视频

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/437330/172093605-b1d7dbe9-bc5a-4e04-a71d-a98f4a776bc5.mov

- MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports) 2 GHz Dual-Core Intel Core i5
-   macOS Monterey 12.3.1
-   safari  Version 15.4 (17613.1.17.1.13)

**Additional context**

使用是的vue2的版本，官方应该用的是vue3版本，在同一个浏览器下没有上述问题。

**Comment by yanmao-cc** [comment]
vue插件 和 engine 都是什么版本？

**Comment by yanmao-cc** [comment]
我在 https://github.com/zb201307/am-editor-vue2 中也没有复现

**Comment by rustbomber** [comment]
> vue插件 和 engine 都是什么版本？

"vue": "^2.6.11",
"@aomao/engine": "^2.9.9",

**Comment by rustbomber** [comment]
> 我在 https://github.com/zb201307/am-editor-vue2 中也没有复现

我试试这个，看会不会

**Comment by rustbomber** [comment]
> 我在 https://github.com/zb201307/am-editor-vue2 中也没有复现

在三台Mac上试过了，发现在1台 macos mojave系统的浏览器（safari  12.1.2）不会卡顿，另外两台 macOS Monterey 12.3.1（safari 15.4）会卡顿

神奇...

**Comment by yanmao-cc** [comment]
可以录制一个性能分析吗？
![image](https://user-images.githubusercontent.com/55792257/172981835-7fd7ffee-fa74-459f-8b68-55692500e613.png)
主要看他的调用树用的每个活动的用时
![image](https://user-images.githubusercontent.com/55792257/172981942-9035f82d-15f4-4510-ae50-241054b45b57.png)

**Comment by rustbomber** [comment]
是用这个时间线录吗，我一点录制，界面基本就卡死了..
![image](https://user-images.githubusercontent.com/437330/177113547-a7dc2ef8-c083-4a25-abc3-485454f471b5.png)
