### ISSUE TITLE
附件下载的时候a标签上可以添加一个download属性吗

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#183]
由于后端存储没有加上文件的后缀文件点击下载按钮变成了打开链接
![image](https://user-images.githubusercontent.com/20843521/172285599-469f44d6-7093-4e92-9e5c-21ed6db869e4.png)
期望，工具组件可以对下载按钮统一增加download-"文件名与后缀"

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/plugin/plugin-file#file-%E5%8F%AF%E9%80%89%E9%A1%B9

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/plugin/plugin-file#%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE
