### ISSUE TITLE
有办法把html直接存在mongo里面吗，我感觉批量导出，是没有很好的办法实现

### ISSUE THREAD

**Issue by fkxgood** [red-axe/am-editor#186]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fkxgood** [comment]
作者您好，开源辛苦。
我这边因为某些业务，需要进行批量导出，然而没有很好的办法，因为getHtml()方法只有前端有，没有方式让前端一次返回所有的html供后端一次导出。

**Comment by yanmao-cc** [comment]
1. 保存的时候或值变更时直接把 html 存到数据库
2. 遍历 MongoDB 中的 json，自行拼接成 html
3. 在前端批量获取到 value 或者 json，使用 new Parser(engine, value).toHTML() 或 toDOM 把 json 转成 value

**Comment by yanmao-cc** [comment]
json 是 https://github.com/ottypes/json0 格式的。
难点在于卡片，不同的卡片转换成 html 的样式不一样的，现已有的所有卡片默认都有 parserHtml 方法来根据 card 的 value 转换成卡片。如果服务端再写一套估计得看看默认转换的方法和样式。或者继承卡片插件，重写 parserHtml 做成自己定义的html风格
