### ISSUE TITLE
文件配置下载无效

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#194]
![image](https://user-images.githubusercontent.com/20843521/176075920-32b28213-daca-47b5-bae7-9cfa215bfc1f.png)
![image](https://user-images.githubusercontent.com/20843521/176076138-0271db6f-a8c9-4471-be00-81d57a275427.png)

**Comment by yanmao-cc** [comment]
[file-uploader]
[file]: {
onDownload
}
这是两个插件
