### ISSUE TITLE
Is there a way to install all plugins with one-time installation？有没有办法一次性安装所有插件

### ISSUE THREAD

**Issue by superbogy** [red-axe/am-editor#202]
When I wanna install all plugins I need to install all plugins one by one. And there are so many plugins, It is quite uncomfortable and inconvenient. I think it is better to put all plugins as a package.
The same thing occurs when I want to upgrade the editor to the latest version. 

当我想要安装所有插件的时候，我需要把所欲的插件一个一个安装，而且这里有那么多插件，使得安装起来相当的麻烦。我认为最好能把所有的插件打成一个包然后让用户自行选择自己需要的插件。
同样的，升级编辑器版本的时候也箱单的麻烦

**Comment by yanmao-cc** [comment]
现在比较好的方法是直接改 package.json 的版本号，然后 npm install ...

**Comment by superbogy** [comment]
@yanmao-cc 感谢回复
我看了一下每个 plugin 都有自己的版本号以及对应的 engine 版本号，这样如果出现了 plugin 和 engine 不兼容的时候会很头疼，我还是希望能提供一个 plugins 统一的包会更好。
BTW plugin  的 `dependencies` ->  `@aomao/engine` 换成 `peerDependencies` -> `@aomao/engine` 可能会更妥一些
ref: https://github.com/vuejs/vuex/blob/28630911b847ac36ac96e73fed7df9c07611defb/package.json#L56
