### ISSUE TITLE
表格的popup如何配置

### ISSUE THREAD

**Issue by hhllee** [red-axe/am-editor#203]
![image](https://user-images.githubusercontent.com/57935206/177735949-3374bbc5-f0e3-451a-ab81-7a89539e3e30.png)

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/docs/faq#%E5%A6%82%E4%BD%95%E5%AE%9A%E5%88%B6%E5%8D%A1%E7%89%87%E5%B7%A5%E5%85%B7%E6%A0%8F
