### ISSUE TITLE
关于编辑器监听blur问题+图片大小+高版本监听change问题

### ISSUE THREAD

**Issue by Stars0518** [red-axe/am-editor#210]
目前是将编辑器做成受控组件，需要在失焦和change的时候做一些处理。
1、但是现在只能通过监听失去焦点事件，在点击上传图片或者快捷键打开功能就会触发失焦，导致我无法正确的获取用户真正意义上的失焦。
2、当我升级高版本时，监听change事件无法获取编辑器里的value
3、关于image插件中的maxHeight，有时不生效。我目前通过自定义上传解决了尺寸问题。

主要想解决第一点，目前没有替代方案。

**Comment by yanmao-cc** [comment]
本身任意点击html标签，浏览器都会把光标聚焦到鼠标点击的目标上的。
这个一个浏览器行为在 mousedown 的事件触发的时候就会去更改，可以在 mousedown 里面使用 e.preventDefault() 来阻止默认行为

现在的 change 事件不会给value，需要自己使用 engine.getValue() 获取
