### ISSUE TITLE
[Bug]@aomao/plugin-lightblock is not in the npm registry

### ISSUE THREAD

**Issue by lixiaoming-bit** [red-axe/am-editor#213]
pnpm add @aomao/plugin-lightblock
Registry has been set to: https://registry.npmmirror.com/

 ERR_PNPM_FETCH_404  GET https://registry.npmmirror.com/@aomao%2Fplugin-lightblock: Not Found - 404

@aomao/plugin-lightblock is not in the npm registry, or you have no permission to fetch it.
No authorization header was set for the request.

大佬看一下
@aomao/plugin-lightblock 这个库不存在

**Comment by yanmao-cc** [comment]
好了
