### ISSUE TITLE
自定义上传Vue版本js有吗？

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#214]
自定义上传Vue版本js有吗？这边看实例写的ts很多报错和方法不存在

**Comment by yanmao-cc** [comment]
ts 擦掉类型不就是js吗？

**Comment by smallCF** [comment]
ts我是可以用的，但是里面很多参数不存在，
![image](https://user-images.githubusercontent.com/50435732/181668297-95d51420-5e6c-448a-8246-884379939e9a.png)
像这种参数，明明是不存在的，这种是不是用values.info.src，还是说有入参的src？

**Comment by yanmao-cc** [comment]
values.info.src ，入参也没有 src 呀，这里把图片文件转存base64呗
