### ISSUE TITLE
关于中文输入时未选中文字直接点击编辑器外部，getValue拿不到值的问题

### ISSUE THREAD

**Issue by Stars0518** [red-axe/am-editor#217]
![image](https://user-images.githubusercontent.com/54577796/181740031-509f1e16-5d77-4356-91ce-a578a11f246a.png)
如图所示，在首次输入的过程中没有中文在内时，点击编辑器外部，engine.isEmpty()为true，并且engine.getValue()中也没有输入的文案。这种需要怎么解决？
我想尝试用Input，但不知道如何使用。
![image](https://user-images.githubusercontent.com/54577796/181741038-6a8abf9b-ed2d-48af-b9ec-1a639f9e4c6c.png)

**Comment by yanmao-cc** [comment]
什么版本，没有复现

**Comment by yanmao-cc** [comment]
在外部节点的mousedown 里面 e.preventDefault 可以阻止吧。因为点外面失焦了，本身组合输入没有完成就会取消掉输入了，输入法自身行为
