### ISSUE TITLE
单击回车换行会渲染两个DOM，toolbar

### ISSUE THREAD

**Issue by Freeaii** [red-axe/am-editor#220]
<img width="1570" alt="截屏2022-08-02 下午2 23 48" src="https://user-images.githubusercontent.com/75149363/182306107-658eb64c-968a-4c5e-958b-0d9f964cc053.png">

**Comment by Freeaii** [comment]
toolbar引入后样式也有点问题

**Comment by yanmao-cc** [comment]
无法复现，你应该是new了多个 engine

**Comment by Freeaii** [comment]
> 

一针见血，原来是我react重新起的项目包裹了StrictMode，所以导致useEffect会渲染两次，生成两个engine实例对象，但是这个toolba样式依旧是有一点问题

**Comment by Freeaii** [comment]
<img width="670" alt="截屏2022-08-02 下午2 38 53" src="https://user-images.githubusercontent.com/75149363/182308553-ef3ed211-98c7-4b75-be8c-a63323eae288.png">

**Comment by yanmao-cc** [comment]
啥问题，看不出来

**Comment by Freeaii** [comment]
<img width="1320" alt="截屏2022-08-02 下午2 42 51" src="https://user-images.githubusercontent.com/75149363/182309218-bd79f46a-965a-4474-a54d-3bfe1989f764.png">
就好像是toolbar样式没加载进来一样，这是一个新起的测试项目，未引入任何其他样式。

**Comment by yanmao-cc** [comment]
应该没引入 antd 样式？

**Comment by Freeaii** [comment]
万岁！解决了，跪谢大佬
