### ISSUE TITLE
编辑器有集成类似Draw.io这样流程图的案例吗

### ISSUE THREAD

**Issue by virtualwj** [red-axe/am-editor#222]

**Comment by yanmao-cc** [comment]
没有，用ifrmae 或者 embed 插件

**Comment by zhaodeezhu** [comment]
结合drawio实现的绘图功能
相关介绍的公众号：
[drawio和am-editor强强联合，实现强大的富文本编辑器绘图板块](https://mp.weixin.qq.com/s?__biz=Mzg3NjE2MDI1NA==&mid=2247483699&idx=1&sn=8b1cb57cea0002c35832067a956d6e66&chksm=cf3734a2f840bdb4cddc037153b55e011bf5273caa196bfa75c71cec30b6a064e1495bdf6cbf#rd)
示例项目：
[xioo-docs](https://github.com/zhaodeezhu/xioo-docs)
可以作为参考
