### ISSUE TITLE
Wanna create a draw(base on X6) plugin. Is there any document to introduce how to write a plugin?

### ISSUE THREAD

**Issue by superbogy** [red-axe/am-editor#225]
**Is your feature request related to a problem? Please describe.**
I'm writing a flow graph app and wanna integrate it into `am-editor`, but after I read the document, I don't how to start my work

**Describe the solution you'd like**
Is there a page to interpret how the plugin works, a document, or a diagram?

**Describe alternatives you've considered**
The diagram would hold a bunch of JSON data, so how to keep this kind of data in the plugin(engine or any other place)?

**Additional context**
none

**Comment by yanmao-cc** [comment]
可以通过这个卡片去做 https://editor.aomao.com/zh-CN/plugin/tutorials-card

**Comment by superbogy** [comment]
awesome! 感谢
