### ISSUE TITLE
光标变动后报错

### ISSUE THREAD

**Issue by Freeaii** [red-axe/am-editor#226]
以下是错误信息：
<img width="1917" alt="截屏2022-08-06 下午9 17 06" src="https://user-images.githubusercontent.com/75149363/183250737-d621de54-8d87-43b6-8f41-8b77127a49b3.png">
以下是错误发生位置：
<img width="1707" alt="截屏2022-08-06 下午9 16 57" src="https://user-images.githubusercontent.com/75149363/183250745-7b48fbc1-8057-4b21-9b00-0612b9d4f4b8.png">

光标改变后产生此错误

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/plugin/plugin-mark-range#%E6%A0%87%E8%AE%B0%E7%B1%BB%E5%9E%8B%E9%9B%86%E5%90%88 你的这个配置没有设置吧
