### ISSUE TITLE
vue2 项目中引入编辑器，字体未安装，有序和无序列表数字不显示问题

### ISSUE THREAD

**Issue by newWebTimes** [red-axe/am-editor#227]
![image](https://user-images.githubusercontent.com/19962540/183333422-b84efa95-d42e-419f-a2a2-6581933736ec.png)
![image](https://user-images.githubusercontent.com/19962540/183333475-f223c284-fe9d-4b70-9636-df0e23f7bd49.png)

**Comment by yanmao-cc** [comment]
那你电脑上有什么字体，序号都是浏览器上ul li默认设置的

**Comment by newWebTimes** [comment]
> 那你电脑上有什么字体，序号都是浏览器上ul li默认设置的

目前调试环境用的是本地localhosts的，在官网访问，字体和列表的图标正常，不明白不显示的原因。电脑中的字体是访问https://at.alicdn.com/t/font_1456030_lnqmc6a6ca.ttf?t=1638071536645下载安装的

**Comment by yanmao-cc** [comment]
你下的是图标字体，跟本身电脑字体没关系。那个检测字体只是检测你电脑系统上面安装了的哪些字体

**Comment by newWebTimes** [comment]
> 你下的是图标字体，跟本身电脑字体没关系。那个检测字体只是检测你电脑系统上面安装了的哪些字体

![image](https://user-images.githubusercontent.com/19962540/183336062-b6934426-06d6-4a38-b1af-392f8f89b7db.png)
电脑本身带了这些字体，编辑器显示字体未安装，代码中需要额外配置嘛

**Comment by newWebTimes** [comment]
我用的是 am-editor-toolbar-vue2 1.1.19版本，引入toolbar后显示字体未安装

**Comment by yanmao-cc** [comment]
这个只是检测你的浏览器上面是否能支持这个字体，支持就可以用，不支持也没关系，不能使用 fontfamily 设置字体而已，跟其它任何东西没有关系，也没有影响
https://github.com/red-axe/am-editor/blob/master/packages/toolbar/src/utils.ts#L36

**Comment by newWebTimes** [comment]
> 这个只是检测你的浏览器上面是否能支持这个字体，支持就可以用，不支持也没关系，不能使用 fontfamily 设置字体而已，跟其它任何东西没有关系，也没有影响 https://github.com/red-axe/am-editor/blob/master/packages/toolbar/src/utils.ts#L36

我们项目中需要设置这些字体的，这个我应该怎么设置讷

**Comment by yanmao-cc** [comment]
就是在你的浏览器上随便一个节点上设置css  fontFamily，然后他的字体没有变化，文字的宽度也没有变，就是认定他算是没这个字体的。https://github.com/red-axe/am-editor/blob/master/packages/toolbar/src/config/toolbar/fontfamily.tsx 这是默认的字体名称。

fontfamily 默认的工具栏配置 https://github.com/red-axe/am-editor/blob/master/packages/toolbar/src/config/toolbar/index.tsx#L606

自定义工具栏配置
https://editor.aomao.com/zh-CN/config/toolbar#dropdown
