### ISSUE TITLE
plugin-image 插件中 uploader 类的 pasteEach 函数 bug

### ISSUE THREAD

**Issue by DLillard0** [red-axe/am-editor#231]
问题描述：

在调用 engine 的 setHtml 方法中如果是 base64 的 img 标签转换出来的 img card 会是处于 uploading 状态，但是其实应该是 done 状态

可能原因：

![image](https://user-images.githubusercontent.com/53611763/185306273-dcf84ca6-7778-4484-a2d8-e79ab0c9d997.png)

这部分的代码是否写错了？按我的理解如果判断为 base64 图片应该直接置为 done，但是这个代码是置为 uploading

**Comment by yanmao-cc** [comment]
因为base64 太长，建议也是把base64在服务端保存下来，返回url

**Comment by DLillard0** [comment]
> 因为base64 太长，建议也是把base64在服务端保存下来，返回url

好的，谢谢，不过我这边确实存在展示 base64 这种场景，所以我目前只能继承这个 upload 自定义去重写这个方法
