### ISSUE TITLE
我将am编辑器的内容粘贴到另一个am编辑器，图片会丢失

### ISSUE THREAD

**Issue by virtualwj** [red-axe/am-editor#232]
另外想问下，am编辑器支持其它文档，比如confluence的图片粘贴吗

**Comment by yanmao-cc** [comment]
复制就是复制的img html，至于第三方支不支持就是看它怎么解析粘贴板的内容了

**Comment by virtualwj** [comment]
> 


https://editor.aomao.com/  图文混和粘贴在官网示例也是不行的，被转换为了<br/>

**Comment by yanmao-cc** [comment]
> > 
> 
> https://editor.aomao.com/ 图文混和粘贴在官网示例也是不行的，被转换为了br标签

如果你是从word复制，那是不行的，图文混合复制，word会把图片地址转为 file:// js无法绕过浏览器安全限制去访问本地硬盘文件

**Comment by virtualwj** [comment]
> > > 
> > 
> > 
> > https://editor.aomao.com/ 图文混和粘贴在官网示例也是不行的，被转换为了br标签
> 
> 如果你是从word复制，那是不行的，图文混合复制，word会把图片地址转为 file:// js无法绕过浏览器安全限制去访问本地硬盘文件

谢谢
