### ISSUE TITLE
取文档的时候，文档中的表格会被编码，导致无法用ES做搜索

### ISSUE THREAD

**Issue by virtualwj** [red-axe/am-editor#233]
![image](https://user-images.githubusercontent.com/43001833/186092055-a627e5fb-7051-49c3-9d29-5b6f1eca9664.png)
见上图，请问是处于什么考虑对表格做编码

**Comment by yanmao-cc** [comment]
你可以使用 getHtml 后的html去做索引

**Comment by virtualwj** [comment]
> 你可以使用 getHtml 后的html去做索引

那存入数据库中的应该是getContent还是getHtml

**Comment by yanmao-cc** [comment]
为啥不一起呢？

**Comment by virtualwj** [comment]
这样数据库会不会有些冗余，有没有考虑统一下，输出为一种格式，现在既有content也有html，不太理解为什么两者要分开

**Comment by yanmao-cc** [comment]
> 这样数据库会不会有些冗余，有没有考虑统一下，输出为一种格式，现在既有content也有html，不太理解为什么两者要分开

content 内的表格是按特点格式去做的，渲染后能够还原交互效果，html就纯粹静态的html，方便做seo，使用 setHtml 也能准确还原，只是解析需要一些性能

**Comment by virtualwj** [comment]
> > 这样数据库会不会有些冗余，有没有考虑统一下，输出为一种格式，现在既有content也有html，不太理解为什么两者要分开
> 
> content 内的表格是按特点格式去做的，渲染后能够还原交互效果，html就纯粹静态的html，方便做seo，使用 setHtml 也能准确还原，只是解析需要一些性能

可以加您个微信吗

**Comment by yanmao-cc** [comment]
有个QQ群可以先加一下 907664876

**Comment by virtualwj** [comment]
> > 这样数据库会不会有些冗余，有没有考虑统一下，输出为一种格式，现在既有content也有html，不太理解为什么两者要分开
> 
> content 内的表格是按特点格式去做的，渲染后能够还原交互效果，html就纯粹静态的html，方便做seo，使用 setHtml 也能准确还原，只是解析需要一些性能

value和html互相转换，这个有提供方法吗

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/api/parser#tohtml
