### ISSUE TITLE
通过View渲染的图片没有预览大图的交互功能

### ISSUE THREAD

**Issue by Stars0518** [red-axe/am-editor#238]
view.current = new View(viewRef.current, {
        plugins,
        cards,
      });

我使用这种方式渲染后端返回的数据，图片正常显示，但是没有预览大图的交互功能。
图一：正常预览图
![image](https://user-images.githubusercontent.com/54577796/187117278-3df2cb3d-cff2-4c33-b392-275eff08af92.png)
图二：编辑时有预览图标
![image](https://user-images.githubusercontent.com/54577796/187117358-71bc09fc-160a-49df-99f3-d03d2fe130b0.png)

**Comment by yanmao-cc** [comment]
如何复现？

**Comment by Stars0518** [comment]
通过View的都没有呀

**Comment by yanmao-cc** [comment]
没复现

**Comment by Stars0518** [comment]
"@aomao/engine": "^2.7.5
"@aomao/plugin-indent": "^2.7.5",
版本是这个的时候

**Comment by Stars0518** [comment]
我尝试升级版本就可以用了
