### ISSUE TITLE
setHtml  reuse the dom attribute  

### ISSUE THREAD

**Issue by wwhwwhwwh** [red-axe/am-editor#239]
**Describe the bug**
通过 setHtml 渲染 ，getValue 返回的值已经有 data-id="d3f9c95a-2Yl0BBUh", 相同的内容 setHtml 又会更新生成新的
data-id，再次渲染对比DOM还会触发change ,实际只有data-id 变了，其他内容没改变 。

**To Reproduce**
可能的解决思路:

1.复用 getValue 返回的 data-id  等DOM 属性
2.暴露一个方法 可以对比出2次的的内容是否相同
3. getValue 返回可传参  去除像 data-id 属性

**Comment by yanmao-cc** [comment]
setHtml 会新生成是这个意思吗？

**Comment by wwhwwhwwh** [comment]
对。getValue 和 setHtml，没改变的情况下，获取到的值应该是一样的，就因为data-id 变化了

**Comment by wwhwwhwwh** [comment]
setHtml 还有这个问题，setValue 已经修复了
[demo](https://github.com/wwhwwhwwh/am-editor-demo-vue2.git)

**Comment by yanmao-cc** [comment]
未复现，每次设置 `<b>加粗</b> <br /> ### 标题 <br />` 都会生成p节点和id是正常现象
![image](https://user-images.githubusercontent.com/55792257/189334105-75ab8964-cf9e-47b7-a245-513ef5a5dfc7.png)

**Comment by yanmao-cc** [comment]
想要聚焦到最后，可以这样：`this.engine.setHtml(this.currentValue, () => {}).focus(false);`

**Comment by wwhwwhwwh** [comment]
测试过。如果在中间编辑，就会强制将光标定位到最后

**Comment by yanmao-cc** [comment]
> 测试过。如果在中间编辑，就会强制将光标定位到最后

那你预期是要定在哪里？

**Comment by wwhwwhwwh** [comment]
在中间编辑，不希望setHtml 之后光标就变到开头或结尾跳。期望在原来编辑的处，就是<cursor />的位置

**Comment by yanmao-cc** [comment]
setHtml 将会完全把内容替换掉，如何确定之前的内容所在光标在新内容的位置？这个也只能你自己在编辑器外操作计算range了
