### ISSUE TITLE
e.upload.addEventListener is not a function

### ISSUE THREAD

**Issue by mk965** [red-axe/am-editor#242]
**Describe the bug**
vue2版本
本地跑没问题，线上编译后上传图片报 `e.upload.addEventListener is not a function` 

**Screenshots**
![image](https://user-images.githubusercontent.com/30465793/187585641-0a7ddb1f-038f-483b-90d4-335be56ec3bf.png)
![image](https://user-images.githubusercontent.com/30465793/187587265-ba4ee80c-87fa-4096-9064-d465bbd9cc06.png)

**Desktop (please complete the following information):**

-   Browser [chrome]
-   Version [2.9.0]

**Comment by mk965** [comment]
![image](https://user-images.githubusercontent.com/30465793/187587418-562ac410-5c40-403d-a384-60e64ebcb8cd.png)

**Comment by yanmao-cc** [comment]
可能你的浏览器不支持 XMLHttpRequest

**Comment by mk965** [comment]
浏览器支持，本地运行没问题，线上编译后会报这个

> 可能你的浏览器不支持 XMLHttpRequest

**Comment by yanmao-cc** [comment]
console.log(new window.XMLHttpRequest().upload)

**Comment by mk965** [comment]
![image](https://user-images.githubusercontent.com/30465793/187588217-7f7cf98a-3ce4-451e-a912-963b3a3f6f5a.png)

**Comment by mk965** [comment]
> console.log(new window.XMLHttpRequest().upload)

![](https://user-images.githubusercontent.com/30465793/187588217-7f7cf98a-3ce4-451e-a912-963b3a3f6f5a.png)

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/187588362-14b44a41-8cb6-4413-b686-852d40528178.png)

**Comment by yanmao-cc** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by mk965** [comment]
> console.log(new window.XMLHttpRequest().upload)

XMLHttpRequest 被复写了，一开始没发现，非常感谢耐心解答，我让我们组的都来点个star
