### ISSUE TITLE
在调试协同发现一个用户在浏览器开两个页签会两个头像

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#247]
需求：想一个用户就一个头像，发现在用户链接成功后永远都会是新增一个
![示例1](https://user-images.githubusercontent.com/20843521/188117532-81ee968e-96cb-41c5-b419-f1f13ef90507.jpg)

**Comment by yanmao-cc** [comment]
这个只是demo数据，你可以随意修改

**Comment by TaihuLight** [comment]
@chunyangyang @big-camel 如何在退出某协同用户退出编辑页面时，强行保存一次当前内容并结束当然用户的连接？

**Comment by big-camel** [comment]
> @chunyangyang @big-camel 如何在退出某协同用户退出编辑页面时，强行保存一次当前内容**并**结束当然用户的连接（类似 [itellyou](https://github.com/big-camel/itellyou 中手动保存功能）？
> 
> 最新版的aomao是否可以采用 https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/plugins/test/component/index.tsx 所示的方法实现 手动保存并从当前文档中移除该用户？

手动调用YjsEditor.disconnect 和保存就可以
