### ISSUE TITLE
编辑过程中引入的图片或其他资源问题

### ISSUE THREAD

**Issue by Freeaii** [red-axe/am-editor#248]
编辑过程中，有没有什么方式去监听图片、视频、文件的删除吗？这样可以同时删除服务器上存储的对应文件。

**Comment by yanmao-cc** [comment]
可以比较值的变化吧，然后遍历查找对应的card。但是有一个副作用，就是删除了再撤销怎么办呢，或者重做呢？

**Comment by Freeaii** [comment]
那我还是后端专门写一套方法在保存文章的时候统一处理吧，不然确实开销挺大的。
