### ISSUE TITLE
设置行高

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#249]
设置行高后，下拉行高对应行的高度正确了，但是再移动回去行高显示默认

**Comment by smallCF** [comment]
使用的版本是am-editor-toolbar-vue2@1.0.21和@aomao/engine@2.8.18

**Comment by smallCF** [comment]
是否是这边版本存在这个问题

**Comment by yanmao-cc** [comment]
不然为啥要迭代

**Comment by smallCF** [comment]
好的，那是只需要am-editor-toolbar-vue2@1.0.21迭代吧

**Comment by yanmao-cc** [comment]
engine

**Comment by smallCF** [comment]
好的，我先看看tag是哪个版本修复的

**Comment by smallCF** [comment]
感谢

**Comment by smallCF** [comment]
![image](https://user-images.githubusercontent.com/50435732/188531852-082a0692-858b-4f3f-adfa-4efd4424f111.png)
engine更新到了2.9.38 后，还是存在这个问题，是否还需要更新其他插件

**Comment by yanmao-cc** [comment]
editor.aomao.com 上面没有复现，你应该把所有的插件都更新到 2.9 以上

**Comment by smallCF** [comment]
![image](https://user-images.githubusercontent.com/50435732/188579370-fd41a65e-bb03-4ce3-a800-2de1387738a7.png)
我单独弄了一个项目，也不会回显行高
![image](https://user-images.githubusercontent.com/50435732/188579602-dc76ee71-6539-4db5-bef9-f9d28fefd616.png)

**Comment by yanmao-cc** [comment]
那给个复现吧

**Comment by smallCF** [comment]
这个是那个demo


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "red-axe/am-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [red-axe/am-editor] 设置行高 (Issue #249)





 
那给个复现吧

**Comment by yanmao-cc** [comment]
https://github.com/zb201307/am-editor-vue2 在上面未复现

**Comment by smallCF** [comment]
你的那个demo不是用的vue2那个插件

**Comment by yanmao-cc** [comment]
> 

那用的是啥。。。，我vue2插件还是用这个开发的呢

**Comment by smallCF** [comment]
am-editor-toolbar-vue2这个依赖有问题
[@aomao/engine](https://github.com/zb201307/am-editor-vue2)这个地址里面用的是@aomao/toolbar

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/188602795-98daa022-7ef2-40ca-b073-6480bc6d760c.png)
am-editor-toolbar-vue2 这个插件就是在这个项目里面做的 https://github.com/zb201307/am-editor-vue2
