### ISSUE TITLE
可以使用egg.js启动协同服务吗

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#251]
示例ot-serve是用的express,项目想用egg.js有没有示例帮助下

**Comment by yanmao-cc** [comment]
有啥不一样吗？差别不是很大呀，会用 egg.js 那 express 不是很简单吗？

**Comment by chunyangyang** [comment]
> 
egg是用egg-socket.io
还不是很熟悉egg

**Comment by yanmao-cc** [comment]
我对这个东西跟你差不多。。。
