### ISSUE TITLE
一个用户多个socket的情况

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#252]
需求：想一个用户只能有一个socket，后面再来连接就删除之前的，或者保留现在的？有没有办法去做？

**Comment by yanmao-cc** [comment]
当然可以呀，这功能你想怎么写就怎么写，跟编辑器没有关系

**Comment by chunyangyang** [comment]
这种建议是写在socket服务里连接去判断，还是用个数据表来记录好

**Comment by yanmao-cc** [comment]
看你需求，都可以的
