### ISSUE TITLE
自定义card插件的toolbar执行操作后不自动关闭，一直显示

### ISSUE THREAD

**Issue by chun222** [red-axe/am-editor#253]
我执行删除后，元素确实已经删除，但是这个toolbar会一直在：
![image](https://user-images.githubusercontent.com/57406062/190549415-061fa956-fca0-40c0-b414-a0117cde7bd6.png)

![image](https://user-images.githubusercontent.com/57406062/190549449-d9202276-75b8-4370-b8db-325bc8c9d6f1.png)

我就是按这个文档写的：
https://editor.aomao.com/zh-CN/plugin/tutorials-card#vue3-%E5%8D%A1%E7%89%87%E6%8F%92%E4%BB%B6%E7%A4%BA%E4%BE%8B

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor-vue3-demo/blob/main/src/plugins/test/index.ts

**Comment by chun222** [comment]
谢谢作者  好快的issue响应！！！为你打call
