### ISSUE TITLE
如何自定义inline插件 

### ISSUE THREAD

**Issue by chun222** [red-axe/am-editor#254]
作者你好，我想做一个行内插件，比如：我想插入一个input标签，现在用card组件已经实现，但是我发现card组件最后解析出来的html好复杂，我想简单点，能不能自定义一个inline插件，然后还具有想card一样的toolbar 或者 让card插件导出的html变得简单点

**Comment by yanmao-cc** [comment]
inline 只能像 a 标签那样，其它工作做起来比较复杂。card 可以自己解析成你想要的html，可以参考一下其它插件实现

**Comment by chun222** [comment]
> inline 只能像 a 标签那样，其它工作做起来比较复杂。card 可以自己解析成你想要的html，可以参考一下其它插件实现

自定义的card可以想办法处理，那个table插件能处理吗  导出的数据实在太复杂了

**Comment by yanmao-cc** [comment]
无法处理了，本身它就有那么复杂
