### ISSUE TITLE
Vue3  版本代码块放大后，会出现样式问题。

### ISSUE THREAD

**Issue by Rudy24** [red-axe/am-editor#261]
【这里是正常的效果】
![I}~~FO(W~`{5)W1{G)M41OL](https://user-images.githubusercontent.com/12670705/192919383-d0d53bcc-a702-4cbc-a191-9dd32d2f8127.jpg)
【这里是放大后（F11）的效果】
![1SH9Q @J %F3FH~N79_ Q3](https://user-images.githubusercontent.com/12670705/192919537-cdf8f288-6e4a-4c5b-a081-99a39a70892d.jpg)

放大后代码块的样式发生了偏离。

**Comment by yanmao-cc** [comment]
![image](https://user-images.githubusercontent.com/55792257/194585060-11b1b761-d1c9-409c-bd54-bf4265a0e8e6.png)
https://github.com/red-axe/am-editor-vue3-demo 在这上面未复现

**Comment by Rudy24** [comment]
> ![image](https://user-images.githubusercontent.com/55792257/194585060-11b1b761-d1c9-409c-bd54-bf4265a0e8e6.png) https://github.com/red-axe/am-editor-vue3-demo 在这上面未复现

已找到问题所在，是我的业务代码触发了这个问题，马上关掉issue
