### ISSUE TITLE
mention 这个添加默认值得格式是怎么样的呢？

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#264]
配置的default也没有生效
![image](https://user-images.githubusercontent.com/50435732/195315065-cb007d94-3285-4742-a745-96136fde9545.png)

**Comment by smallCF** [comment]
![image](https://user-images.githubusercontent.com/50435732/195487815-cff2008c-16ae-47b5-aa9d-315ab1530cc0.png)
麻烦问一下，这样写的rereturn 数组并不会渲染下拉列表，只有default生效，是有啥子配置的不对嘛？

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/plugin/plugin-mention#%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE 
明显是返回 {result: true, data: []}

**Comment by smallCF** [comment]
感谢，我看错了，只看到data去了




Szz'
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "red-axe/am-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [red-axe/am-editor] mention 这个添加默认值得格式是怎么样的呢？ (Issue #264)





 
https://editor.aomao.com/zh-CN/plugin/plugin-mention#%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%93%8D%E5%BA%94%E6%95%B0%E6%8D%AE
 明显是返回 {result: true, data: []}
