### ISSUE TITLE
在自定义的Card组件内，插入内联的Card组件

### ISSUE THREAD

**Issue by dodospace** [red-axe/am-editor#269]
我在自定义的Card组件内，插入一个内联的自定义组件，会导致光标位置跳到这个插入的组件前面，请问这个问题要如何解决？

**Comment by yanmao-cc** [comment]
自定义的是 Blcok 还是 inline 卡片？是否可编辑？
插入内联的自定义组件，是可编辑卡片？还是普通卡片？
另外截图提供一下dom结构看看

**Comment by dodospace** [comment]
自定义的是 Blcok，是否可编辑怎么判断，还有目前我使用的版本是2.4.3。之前有个QQ群，是解散掉了吗？

**Comment by yanmao-cc** [comment]
2.4 。。。那确实太老了。QQ群还在： 907664876
