### ISSUE TITLE
工具栏按钮及内容不显示

### ISSUE THREAD

**Issue by xiaoxiao-96** [red-axe/am-editor#273]
vue2中使用am-editor-toolbar-vue2时工具栏按钮及其内容不显示，检查器检查对比正常显示的工具栏，发现是button元素中间少了span元素，这种情况是什么原因导致的呢？
<img width="960" alt="0ef04091a49fa5f259df1de51f37d0a" src="https://user-images.githubusercontent.com/117247660/202345217-aa304c46-1e50-43c8-8bb1-ed646ad10b6c.png">
![1668654406101](https://user-images.githubusercontent.com/117247660/202345220-8a01cbf9-9ac2-4c40-84c9-80ace2ea165f.jpg)

**Comment by yanmao-cc** [comment]
element-ui 和 ant-design-vue 冲突了吧

**Comment by xiaoxiao-96** [comment]
之前也考虑过这个可能，但是我在外网试过了，主框架用element-ui，然后再使用vue2的工具栏，也是能正常显示的，不存在冲突，所以现在考虑是不是插件内部引用的依赖没有下全，但是对比了也没发现区别，所以才想说问问您有没有遇到这种情况过，或者能否给出一点查找或解决的思路呢

**Comment by yanmao-cc** [comment]
之前遇到过的也就element-ui冲突了

**Comment by yanmao-cc** [comment]
另外就是 vue存在多个版本

**Comment by xiaoxiao-96** [comment]
真从来没考虑过vue版本的问题，之前vue版本是2.6.10，现在调整到2.6.14，就可以显示了！！！太感谢啦，谢谢作者大大！！！！
