### ISSUE TITLE
setHtml时第一个节点是card时会跳过后续节点的normalize

### ISSUE THREAD

**Issue by Pandooo** [red-axe/am-editor#276]
![企业微信截图_16696937065720](https://user-images.githubusercontent.com/25189437/204434102-2699b7fa-3b5a-4946-9a4c-0ca227ed5da5.png)
![企业微信截图_16696938949149](https://user-images.githubusercontent.com/25189437/204434435-559fc80e-6eff-4e95-826a-d6993dd99673.png)
aomao/engine/dist/index 2903行，node如果是node list(html文本首次被格式化时)的第一个child node是card的情况下，node.isCard()会返回true并跳过后面的while (child)。主要是因为isCard方法中当this是list时this.get()会获取第一个节点用于判断this是否是card

**Comment by yanmao-cc** [comment]
因为card的数据都在节点 data-card-value 上面，他的子节点都是通过这个value去渲染的。所以没有必要遍历它的子节点------------------------------------------------------------------
***@***.***>
日　期：2022年11月29日 11:53:41
***@***.***>
***@***.***>
主　题：[red-axe/am-editor] setHtml时第一个节点是card时会跳过后续节点的normalize (Issue #276)



 aomao/engine/dist/index 2903行，node如果是node list(html文本首次被格式化时)的第一个child node是card的情况下，node.isCard()会返回true并跳过后面的while (child)。主要是因为isCard方法中当this是list时this.get()会获取第一个节点用于判断this是否是card

**Comment by Pandooo** [comment]
不是遍历card的子节点，是在初次遍历整个文档的htm时出的问题，fragment的第一个节点是card时node.isCard会认为fragment整个都是card
![企业微信截图_16696980785352](https://user-images.githubusercontent.com/25189437/204443331-d1d952b6-b5ce-4ee7-aac9-83580b0a2398.png)

**Comment by yanmao-cc** [comment]
有测试数据吗？另外你当前engine的版本是多少？
