### ISSUE TITLE
是否可以支持拖拽

### ISSUE THREAD

**Issue by Mowmowj** [red-axe/am-editor#277]
每个模块前面直接是否能加一个 拖拽图标 实现类似飞书、语雀左边的拖拽功能呢

**Comment by Mowmowj** [comment]
add: 请问可以手动开启每行都显示拖拽的图标吗
另外观察到蓝湖在拖拽时 会在预放置位 画出蓝色高亮辅助线  没有时间的话 请问可以提供下思路吗 我可以尝试参与

**Comment by yanmao-cc** [comment]
am-editor 现在没有这个功能。不过巧的是我前两天在做新版本的时候做了这个功能，只能提供一下思路。

- 在编辑器根节点监听 mousemove 事件，然后每次触发获取到对应的节点，有下面几种方式去获取
    * 通过 event.clientX event.clientY 根据坐标去计算
    * 通过 event.target 去计算获取节点
    * 通过 caretRangeFromPoint 原生api根据坐标获取到 Range 对象，然后再获取到节点位置
- 获取到节点后就能通过 getBoundingClientRect 原生api获取到这个节点位置和大小，这样可以根据这些坐标和位置计算放在侧边拖动的 按钮 位置了。
- 在拖动过程中，处理也差不多，得到鼠标位置对应的节点后，计算相对于 mousemove 事件的坐标，得到要放下的位置，这样就可以绘制一条放置位置的线

这里放个新版本的实现代码链接 https://github.com/editablejs/editable/blob/main/packages/plugins/toolbar/src/side/index.tsx 因为新版本完全自己绘制的光标，抛弃了 contenteditable ，所以实现起来跟 am-editor 差别很大，不过思路是差不多一致的

**Comment by Mowmowj** [comment]
感谢提供思路  👍
