### ISSUE TITLE
关于scrollbarModel的问题

### ISSUE THREAD

**Issue by codingCenterFar** [red-axe/am-editor#278]
这里的umi.server.js是打包后的文件
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/116075492/205668538-3a5bb0c0-8602-4b34-9dbe-f92e0217dc87.png">

**Comment by codingCenterFar** [comment]
> https://codemirror.net/5/doc/manual.html#option_scrollbarStyle https://codemirror.net/5/doc/manual.html#addon_simplescrollbars

为啥本地可以，打包到线上就报错了，是依赖的问题吗》

**Comment by codingCenterFar** [comment]
> https://codemirror.net/5/doc/manual.html#option_scrollbarStyle https://codemirror.net/5/doc/manual.html#addon_simplescrollbars

我还特地装了@types/codemirror还是报错，在使用代码块的时候

**Comment by yanmao-cc** [comment]
报啥错，哪一行代码？

**Comment by codingCenterFar** [comment]
> 报啥错，哪一行代码？
打包后的文件运行出错，内容是Kr[e.options.scrollbarStyle] is not a constructor

**Comment by yanmao-cc** [comment]
有没有啥稳定复现的步骤或者代码吗？

**Comment by codingCenterFar** [comment]
> 有没有啥稳定复现的步骤或者代码吗？

复现的话就是本地项目运行时可以正常使用CodeBlock插件，Jenkins打包后就在编辑器页面使用CodeBlock时就报错了，而且点不动。我觉得可能是Codemirror的依赖问题，我发现在CodeBlock这边引入simpleScrollbars的时候依赖指向是根目录的node_modules,而不是插件目录下node_modules的js文件，所以导致没有正常引入simpleScrollbars.js文件，想问问有啥解决办法吗？我在根目录试着安装codemirror库，结果也是报错
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/116075492/205920537-cb2d3158-c9b7-476b-b937-166fe4aa5fb1.png">

**Comment by yanmao-cc** [comment]
正常情况是安装在根目录的node_modules内的。  你看下打包后的混淆代码里面有没有 simplescrollbars就知道了

**Comment by codingCenterFar** [comment]
> 
目前是在我的项目代码中import 了codemirror/addon.scroll/simplescrollbars解决的，但是不知道为什么在插件源码中引入的没有生效
