### ISSUE TITLE
表格右键菜单位置和点击位置不对应

### ISSUE THREAD

**Issue by Re-Li-fe** [red-axe/am-editor#279]
**Describe the bug**
当表格在文档中的高度比较靠下时，右键菜单的位置和点击的位置不对应。
**To Reproduce**
根节点外面就包了一层div
```html
<template>
  <div style="background-color: #f5f5f5">
    <AmToolbar v-if="engine" :engine="engine" :items="toolbarItems" />
    <div style="padding: 4vw 4vw;" ref="container"></div>
  </div>
</template>
```
**Expected behavior**
菜单应该和鼠标右键出现在同一个位置

**Screenshots**
如下图，光标所在的位置是我点击的位置：
![image](https://user-images.githubusercontent.com/74761910/208100495-a4bab519-334c-47d3-8fa4-aa82b2ec79a7.png)
**Desktop (please complete the following information):**

-   OS: windows 10
-   Browser :chrome
-   Version :2.9.33

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/ 
缩小窗口直到出现滚动条也不会出现这个问题。

这个问题主要是 https://editor.aomao.com/zh-CN/config#scrollnode 这个滚动条节点的设置，如果没找到正确的滚动条，那么右键菜单定位的时候就会计算错误，这个位置是一个相对于滚动条的位置

**Comment by Re-Li-fe** [comment]
是，刚才已经发现原因了，如果在外面的div中加一个滚动条就不会出现这个问题了。
此外还想请教一个问题，我刚才把plugins\table\src\component\controllbar.ts第1532行中的`scrollNode`改成`root`发现也能正常使用，为什么要基于滚动条计算呢？

**Comment by yanmao-cc** [comment]
那滚动的时候怎么定位
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年12月16日 23:24:01
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 表格右键菜单位置和点击位置不对应 (Issue #279)

是，刚才已经发现原因了，如果在外面的div中加一个滚动条就不会出现这个问题了。
 此外还想请教一个问题，我刚才把plugins\table\src\component\controllbar.ts第1532行中的scrollNode改成root发现也能正常使用，为什么要基于滚动条计算呢？

**Comment by Re-Li-fe** [comment]
感谢您这么晚还来回复，但是用scrollNode定位好像滚动的时候菜单也不会跟着滚动啊

**Comment by Re-Li-fe** [comment]
明白了，感谢您的回复！
