### ISSUE TITLE
编辑器的@功能如何实现-vue版本

### ISSUE THREAD

**Issue by wakakakk** [red-axe/am-editor#283]
![image](https://user-images.githubusercontent.com/66005999/216524216-5b03975f-8b3a-488e-8c39-52ca0f6577c3.png)

**Comment by big-camel** [comment]
mention 插件本身就是js的，没有使用 vue 或者 react，可以通用

**Comment by big-camel** [comment]
![image](https://user-images.githubusercontent.com/55792257/216524662-3fadae84-2594-4881-b16f-d307f1be1121.png)

这些配置自定义的渲染可以使用 [vue mount api](https://vuejs.org/api/application.html#app-mount) 替换 `ReactDOM.render`
