### ISSUE TITLE
非常迫切需要vue版本的协作demo

### ISSUE THREAD

**Issue by l54808821** [red-axe/am-editor#284]
我按照教程，配置了协作的server和client，但是没有编辑器没有成功。很需要这个demo
https://editor.aomao.com/zh-CN/config/ot
<img width="947" alt="image" src="https://user-images.githubusercontent.com/49773498/216906387-315d8734-2c60-47f4-aa04-f45315e8fcaa.png">

代码：
   //实例化协作编辑客户端，需要传入当前编辑器实例
        const ot = new OTClient(engineInstance);
        // 这里不再需要使用 engine.setValue。只需要在连接的时候把 value 传给 OTClient。在连接到服务端后，如果服务端没有该文档将以默认值创建，否则就返回服务端的最新文档数据
        // 连接协同服务端，如果服务端没有对应docId的文档，将使用 defaultValue 初始化
        // url 服务端ws链接
        // docId 文档的唯一识别id
        // defaultValue 在服务端如果docId对应的文档不存在，将会以这个值创建一个新文档
        const url = "ws://localhost:8080";
        const docId = "test";
        ot.connect(url, docId, value);
        ot.on("ready", (member) => {
          console.log("OT Ready");
        });

**Comment by big-camel** [comment]
给个复现仓库吧

**Comment by l54808821** [comment]
@big-camel https://gitee.com/tuzikuaipao/am-vue3-demo

**Comment by big-camel** [comment]
> @big-camel https://gitee.com/tuzikuaipao/am-vue3-demo
const url = "ws://localhost:8080";

你前端项目地址是 localhost:8080 ，你都没有启动 ot-server 项目吧？那肯定连不上啊

**Comment by big-camel** [comment]
你可以把 ot-server 复制出来，他是一个 nodejs 项目，你需要启动他

**Comment by l54808821** [comment]
您好，ot-server我是已经启动的，看了一下他的默认url就是localhost:8080吧
<img width="350" alt="image" src="https://user-images.githubusercontent.com/49773498/217126155-0101de3a-92ac-4b81-9cdc-1fb118753f76.png">

**Comment by l54808821** [comment]
demo中的端口我改成8082啦
<img width="458" alt="image" src="https://user-images.githubusercontent.com/49773498/217126606-33cb57d2-344b-4307-ab72-2f1f139ffcd0.png">

**Comment by l54808821** [comment]
@big-camel  很感动，可以这么快的回复，这个可能是个私人问题，可以进行赞助私人聊么。我的QQ  237371257
