### ISSUE TITLE
有多人协同详细一点的文档吗

### ISSUE THREAD

**Issue by weishaoy** [red-axe/am-editor#286]
看了多人协同的demo,有很多地方比较疑惑,想问下大佬,有详细一点的文档吗

**Comment by big-camel** [comment]
有哪些疑问，可以先发出来？

**Comment by weishaoy** [comment]
> 有哪些疑问，可以先发出来？
只有react的多人协同demo ,没有vue的多人协同demo,vue里不会用

**Comment by big-camel** [comment]
可以把 ot client 文件复制出来，他是 ts 的里面没有 react 相关东西。 ot-server 项目启动起来，他是 nodejs 的，也没有react 相关的东西

可以看一下这个 issue
https://github.com/red-axe/am-editor/issues/284

**Comment by big-camel** [comment]
还可以看一下他的 demo https://github.com/red-axe/am-editor/issues/284#issuecomment-1419114039

**Comment by weishaoy** [comment]
> 还可以看一下他的 demo [#284 (comment)](https://github.com/red-axe/am-editor/issues/284#issuecomment-1419114039)

好的,感谢,请问可以进行赞助私人聊么,v weiShaoY_
