### ISSUE TITLE
同一个markdown里复制粘贴图片为什么需要重新上传接口，这个能关闭么

### ISSUE THREAD

**Issue by wangjian27** [red-axe/am-editor#287]

**Comment by big-camel** [comment]
同一个markdown？复制的内容对编辑器来说每次都是新的，检测到图片的url自然拿去处理

**Comment by wangjian27** [comment]
我看官网的例子是可以复制粘贴同编辑器的图片做到不调用接口，请问是如何实现？
![image](https://user-images.githubusercontent.com/59763663/218988712-a24c17bc-4978-4403-a9eb-70b62dc27a5c.png)

**Comment by big-camel** [comment]
它复制的还是 aomao.com 的图片地址，isRemote 那里可以设置为外部的图片就会走上传，不是就不上传

**Comment by wangjian27** [comment]
原来如此，感谢
