### ISSUE TITLE
通过后端api拿到带有img标签的数据,回显到富文本里面img标签消失

### ISSUE THREAD

**Issue by JCqiu** [red-axe/am-editor#289]
![image](https://user-images.githubusercontent.com/16211027/219847069-0b936c3d-2b37-4065-aa4c-6d7109be689f.png)
![image](https://user-images.githubusercontent.com/16211027/219847090-901611bc-e96b-4c1a-bc74-6bc60e5927bc.png)

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/219847147-c9a73d70-50a1-4d77-90c4-8b34c85f2e9a.png)

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/219848667-a04547db-4edc-493d-b9ce-eafc4f111b5f.png)
通过断点调试,发现img标签满足某些条件就会被替换成br标签,请问要怎样修改img数据才能跳过这段替换代码

**Comment by big-camel** [comment]
是否有添加 image 和 image-uploader 插件？
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2023年02月18日 15:52:18
***@***.***>
***@***.***>
主　题：Re: [red-axe/am-editor] 通过后端api拿到带有img标签的数据,回显到富文本里面img标签消失 (Issue #289)


 通过断点调试,发现img标签满足某些条件就会被替换成br标签,请问要怎样修改img数据才能跳过这段替换代码

**Comment by JCqiu** [comment]
@big-camel 
![image](https://user-images.githubusercontent.com/16211027/219850217-6df96eba-70b9-4c83-af0a-54583c5bd0f2.png)
是这个么,引入了的

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/219850342-640de5de-c835-47ad-827a-5f94ed6b47a6.png)

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/219850372-138d2634-70ae-496f-acbe-9a666ec6d0d3.png)

**Comment by big-camel** [comment]
使用的setValue 还是setHtml？
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2023年02月18日 16:29:02
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 通过后端api拿到带有img标签的数据,回显到富文本里面img标签消失 (Issue #289)

**Comment by JCqiu** [comment]
@big-camel 用的setValue
![image](https://user-images.githubusercontent.com/16211027/219850806-19c4580b-3b93-49aa-926e-2fac7aaa06c8.png)

**Comment by JCqiu** [comment]
@big-camel 用setHtml就可以了

**Comment by JCqiu** [comment]
@big-camel 
![image](https://user-images.githubusercontent.com/16211027/219851311-3711089e-45dc-457d-8af9-a87b0125e417.png)
![image](https://user-images.githubusercontent.com/16211027/219851320-3cbcc285-8b22-496a-9a13-d353f07efcea.png)
回显图片会加载失败

**Comment by big-camel** [comment]
跨域了？

**Comment by JCqiu** [comment]
@big-camel 不是跨域,我改了上传图片请求地址就能正常了
