### ISSUE TITLE
vue2 toolbar icon 不显示

### ISSUE THREAD

**Issue by xiaojingyuaner** [red-axe/am-editor#291]
![image](https://user-images.githubusercontent.com/24470322/221393508-87eabd3d-525e-4481-981c-e30bbe274413.png)
我用的是vuejs 2.6.11 和提供vue2demo一样，但是icon不显示，用了element-ui，是不是这个ui和ant冲突了，如果是要怎么处理？

**Comment by big-camel** [comment]
vue 版本不一致导致的，升级到 2.6.14 试一下
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2023年02月26日 13:12:28
***@***.***>
***@***.***>
主　题：[red-axe/am-editor] vue2 toolbar icon 不显示 (Issue #291)


 我用的是vuejs 2.6.11 和提供vue2demo一样，但是icon不显示，用了element-ui，是不是这个ui和ant冲突了，如果是要怎么处理？
