### ISSUE TITLE
wujie微前端下,子项目运行富文本,输入内容报错,脱离微前端环境运行正常

### ISSUE THREAD

**Issue by JCqiu** [red-axe/am-editor#292]
**Describe the bug**
![微信图片_20230227180110](https://user-images.githubusercontent.com/16211027/221533581-4488fe19-05d4-4fdc-aa32-aebb57d77a56.jpg)
![微信图片_20230227180114](https://user-images.githubusercontent.com/16211027/221533603-ff7aaf1d-f7a0-4fc7-8b55-f2a571fd5464.jpg)
![微信图片_20230227180119](https://user-images.githubusercontent.com/16211027/221533622-856f1413-acce-452d-ac42-fc04627aa4ac.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by big-camel** [comment]
麻烦给个复现仓库吧

**Comment by JCqiu** [comment]
@big-camel 周末吧,我这几天在加班还没时间
