### ISSUE TITLE
如何关闭schema 的规则，如今的schema 会干掉许多默认的样式，配置了schema 规则也木有效果，还是会干掉好多自己的样式

### ISSUE THREAD

**Issue by frontend-qin** [red-axe/am-editor#293]
![image](https://user-images.githubusercontent.com/26999638/222043319-308e573b-5587-425c-8110-b8ed3564d3d6.png)
![image](https://user-images.githubusercontent.com/26999638/222043353-ed448542-686d-470d-a516-b15f445c18a5.png)

**Comment by big-camel** [comment]
@aomao/engine@2.9.62 增加了 isMerge 参数，schema.add(rule, true) 这样就可以合并到现有规则了

**Comment by lj520github** [comment]
> @aomao/engine@2.9.62 增加了 isMerge 参数，schema.add(rule, true) 这样就可以合并到现有规则了

更新了版本后，没有看到add(rule,true)的重载方法。我看源码里面并没有增加这个方法

**Comment by big-camel** [comment]
> > @aomao/engine@2.9.62 增加了 isMerge 参数，schema.add(rule, true) 这样就可以合并到现有规则了
> 
> 更新了版本后，没有看到add(rule,true)的重载方法。我看源码里面并没有增加这个方法

参数是有的，但是SchemaInterface上面的类型漏了，下一个版本会补上~
