### ISSUE TITLE
清空编辑器内容后，获取到的value是p标签

### ISSUE THREAD

**Issue by JNUfeatherwit** [red-axe/am-editor#294]
理想的情况不是应该是空字符串吗

**Comment by big-camel** [comment]
因为默认需要保留可以编辑的空行，所以有这个，另外你可以通过 engine.isEmpty 来判断是否为空

**Comment by JNUfeatherwit** [comment]
> 因为默认需要保留可以编辑的空行，所以有这个，另外你可以通过 engine.isEmpty 来判断是否为空

了解了，感谢您的及时回复。我在change事件回调那里做下处理就可以了
