### ISSUE TITLE
编辑时插入图片并设置大小，new View().render()的时候图片还是源大小，是我遗漏了啥配置吗？

### ISSUE THREAD

**Issue by WWongs** [red-axe/am-editor#298]
**Describe the bug**
编辑时插入图片并通过图片上面的小工具设置大小（并嵌入行内），new View().render()的时候图片还是源大小。

**To Reproduce**

1. 编辑模式
![image](https://user-images.githubusercontent.com/31298228/224209064-0d982e54-61e8-49f7-9b7d-eaf45dbed6ce.png)

2. 回显render模式
![image](https://user-images.githubusercontent.com/31298228/224209737-a4549836-b7e3-42f6-89d3-8455a434f84c.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by big-camel** [comment]
new View().render() 的是 value 还是html？

**Comment by WWongs** [comment]
我render的是value，html render回显不出来图片。

**Comment by big-camel** [comment]
有没有什么复现的仓库吗？我这边没复现到，也没有第一时间就能想到的问题所在信息
