### ISSUE TITLE
您好！新增的Card插件 block可编辑区 修改哪里可以插入 表格

### ISSUE THREAD

**Issue by huanglishi** [red-axe/am-editor#300]
[![license](https://tuwen.hulingyun.cn/common/uploadfile/getimage?url=resource/uploads/20230313/4326da254651887ffd8f9de2555aad6d.png)](LICENSE)

**Comment by big-camel** [comment]
当前可编辑区插件不能嵌套。。。

**Comment by huanglishi** [comment]
可以修改限制 ，强制插入吗 ，我想用card插件做分页

**Comment by huanglishi** [comment]
> 当前可编辑区插件不能嵌套。。。

可以修改限制 ，强制插入吗 ，我想用card插件做分页

**Comment by big-camel** [comment]
主要是嵌套后的逻辑很复杂，如果要修改，得想办法把这些逻辑重构一下

**Comment by huanglishi** [comment]
> 主要是附后的总编辑很复杂，如果要修改，想办法把这些总编辑重组一下

我查到外部后 在移动进去 表格功能是可以用的，要是能找到限制插入部分代码 直接插入我就可以用了card来分页了
[![license](https://tuwen.hulingyun.cn/common/uploadfile/getimage?url=resource/uploads/20230314/ff5046ec26ea921b06b962e5f57cc5df.png)](LICENSE)

**Comment by big-camel** [comment]
https://github.com/red-axe/am-editor/blob/master/packages/toolbar/src/config/toolbar/index.tsx#L118
工具栏上配置一下 onDisabled 就好了
