### ISSUE TITLE
希望文本能有块的概念，支持拖拽，同行并列，类似于notion

### ISSUE THREAD

**Issue by ityuanying** [red-axe/am-editor#310]
（这并不是一个常规需求，所以或者可以大致了解一下如果需要实现，可以从源码的什么地方去做调整）

**Comment by big-camel** [comment]
这个难度很大，am-editor 不具备这样修改的能力。用 https://github.com/editablejs/editable 这个倒是更容易些

**Comment by ityuanying** [comment]
谢谢解答
