### ISSUE TITLE
同时选择上标样式和下标样式的内容，并选中转为上标，就页面崩溃

### ISSUE THREAD

**Issue by codingCenterFar** [red-axe/am-editor#316]
选择既上标样式又有下标样式的内容，并选中转为上标，就页面崩溃

**Comment by big-camel** [comment]
如何复现？上标和下标现在不能同时设置

**Comment by codingCenterFar** [comment]
> 如何复现？上标和下标现在不能同时设置

就两个字符，一个字符上标，一个字符小标，然后同时选中这两个字符，点击切换上下标就会报错
