### ISSUE TITLE
协作的时候只有光标，其他协作者输入的内容没有变化，可以帮忙看看啥原因嘛

### ISSUE THREAD

**Issue by voneFront** [red-axe/am-editor#321]
项目是多文档 可切换的
<img width="1679" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/d5480897-6e12-42b6-8935-5a2a5f146538">
<img width="1593" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/2501af82-984f-46a5-84ab-cf95cfcbaed0">
切换文档时的监听
<img width="921" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/9cdfcb24-3a66-4c09-8d56-dad69f663d72">
创建 Yjs WebsocketProvider 对象
<img width="1047" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/a05deeb3-9dd1-46ff-b8ab-00dde20976bc">
创建连接的代码
<img width="971" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/f18d1f45-f805-465d-9d12-5a032f061cab">
监听光标事件
<img width="819" alt="image" src="https://github.com/red-axe/am-editor/assets/132646606/2c919969-a139-4510-825c-f70fe747cc8a">

**Comment by big-camel** [comment]
连接后，YjsEditor 没有调用 connect 吧？
```
const editor = engine.current;
		if (!editor || !YjsEditor.isYjsEditor(editor)) return;
		if (connected) YjsEditor.connect(editor);
		return () => {
			YjsEditor.disconnect(editor);
		};
```

**Comment by huangqingkun** [comment]
![image](https://github.com/red-axe/am-editor/assets/38900035/8d024a01-759a-4a28-adf9-e256afb43fa0)
我这边也有一样的问题，只有光标会变化
