### ISSUE TITLE
回车后总是多出一个空行

### ISSUE THREAD

**Issue by mengfei0001** [red-axe/am-editor#330]
![image](https://github.com/red-axe/am-editor/assets/16757966/493f9023-d764-428f-8548-0984e5e49441)

在官方的实例中， 我在hello后面按回车， 总会多出一样

**Comment by wwhwwhwwh** [comment]
默认 配置下 
`autoAppend` 为true：在编辑器尾部单击空白处是否自动添加空行
`autoPrepend` 为true：在编辑器头部单击空白处是否自动添加空行

```js
const engine = new Engine(this.$refs.container, {
      autoAppend :false,
      autoPrepend :false
      config: pluginConfig()
 });
```

**Comment by mengfei0001** [comment]
> 
不是这个问题， 我是在hello回车后， 光标直接跳到了下下行

**Comment by wwhwwhwwh** [comment]
`index.tsx` 如果加了，React.StrictMode ，严格模式下会导致重复渲染，`chang` 事件也会重复执行，需要去除。
```tsx
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

**Comment by mengfei0001** [comment]
感谢老哥， 去除StrictMode 解决问题了
