### ISSUE TITLE
是否可以提供一个添加评论的例子呀？ 

### ISSUE THREAD

**Issue by huangqingkun** [red-axe/am-editor#341]
![image](https://github.com/red-axe/am-editor/assets/38900035/4e77fcd2-96d0-4163-b055-f982b816a3ea)

**Comment by big-camel** [comment]
https://github.com/red-axe/am-editor/blob/master/examples/react/components/comment/index.tsx
现在就只有一个react 的

**Comment by huangqingkun** [comment]
有计划搞vue的例子吗？ 

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月7日 9:53
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

https://github.com/red-axe/am-editor/blob/master/examples/react/components/comment/index.tsx
现在就只有一个react 的

**Comment by huangqingkun** [comment]
另外有个问题想请教下，编辑初始化文档内容时机应该是什么时候？  我现在是在以下事件处理的，大部分情况没有问题，偶尔还是出现先初始化了文档才同步其他协作者的文档



 

发件人: huangqingkun ***@***.*** 
发送时间: 2023年10月7日 12:48
收件人: 'red-axe/am-editor'; 'red-axe/am-editor'
抄送: 'Author'
主题: 答复: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

有计划搞vue的例子吗？ 

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月7日 9:53
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

https://github.com/red-axe/am-editor/blob/master/examples/react/components/comment/index.tsx
现在就只有一个react 的

**Comment by big-camel** [comment]
没计划，差别不大，逻辑都是通用的

**Comment by huangqingkun** [comment]
这个问题可以帮看下吗？

 

发件人: huangqingkun ***@***.*** 
发送时间: 2023年10月7日 12:52
收件人: 'red-axe/am-editor'; 'red-axe/am-editor'
抄送: 'Author'
主题: 答复: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

另外有个问题想请教下，编辑初始化文档内容时机应该是什么时候？  我现在是在以下事件处理的，大部分情况没有问题，偶尔还是出现先初始化了文档才同步其他协作者的文档



 

发件人: huangqingkun ***@***.*** 
发送时间: 2023年10月7日 12:48
收件人: 'red-axe/am-editor'; 'red-axe/am-editor'
抄送: 'Author'
主题: 答复: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

有计划搞vue的例子吗？ 

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月7日 9:53
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

https://github.com/red-axe/am-editor/blob/master/examples/react/components/comment/index.tsx
现在就只有一个react 的

**Comment by big-camel** [comment]
本质上yjs会在浏览器本地和服务器端使用最新的数据覆盖，可以在他们连接后重新设置值，然后编辑器变化后会同步给其它协作者

**Comment by huangqingkun** [comment]
Ok，已经可以了

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月7日 21:17
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

本质上yjs会在浏览器本地和服务器端使用最新的数据覆盖，可以在他们连接后重新设置值，然后编辑器变化后会同步给其它协作者

**Comment by huangqingkun** [comment]
不对，刚才重新测试了下还是不行，你这边编辑的时候什么时候调setHtml()设置值到编辑器的？ 

 

发件人: huangqingkun ***@***.*** 
发送时间: 2023年10月8日 12:44
收件人: 'red-axe/am-editor'; 'red-axe/am-editor'
抄送: 'Author'
主题: 答复: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

Ok，已经可以了

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月7日 21:17
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

本质上yjs会在浏览器本地和服务器端使用最新的数据覆盖，可以在他们连接后重新设置值，然后编辑器变化后会同步给其它协作者

**Comment by big-camel** [comment]
我不会调用 setHtml ，因为 yjs 连上会同步过来的

**Comment by huangqingkun** [comment]
如果你是首个进入编辑文章页面，不调用setHtml，yjs连上后也同步不到数据呀。

 

如果说本来就有另外一个人已经进入编辑页面了并且输入了内容，那么进入编辑页面连上yjs后是能同步到数据的，

 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月8日 19:44
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

我不会调用 setHtml ，因为 yjs 连上会同步过来的

**Comment by big-camel** [comment]
所以等链接好后，再调用 setHtml

**Comment by huangqingkun** [comment]
也不行哦，我这边之前就以为可以，实际连接上数据可能还没有同步到，如下图逻辑可能进入一次编辑页面就会多复制一份内容了，你这边是怎么操作的可以截图我看看你设置值的时机吗？ 



 

发件人: YiYang ***@***.*** 
发送时间: 2023年10月9日 17:06
收件人: red-axe/am-editor
抄送: huangqingkun; Author
主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 

所以等链接好后，再调用 setHtml

**Comment by big-camel** [comment]
我这里也没有例子，可以考虑在yjs服务端初始化文档的时候就设置值？
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2023年10月09日 19:45:37
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341)

 也不行哦，我这边之前就以为可以，实际连接上数据可能还没有同步到，如下图逻辑可能进入一次编辑页面就会多复制一份内容了，你这边是怎么操作的可以截图我看看你设置值的时机吗？ 





 发件人: YiYang ***@***.*** 
 发送时间: 2023年10月9日 17:06 
 收件人: red-axe/am-editor 
 抄送: huangqingkun; Author 
 主题: Re: [red-axe/am-editor] 是否可以提供一个添加评论的例子呀？ (Issue #341) 



 所以等链接好后，再调用 setHtml

**Comment by big-camel** [comment]
const handleCustomMessage = (message: Record<string, any>) => {
      const { action } = message;
      if (action === 'initValue') {
        if (value) {
          engine.current?.setValue(value);
          engine.current?.history.clear();
        }
      } 
      if (yjs && yjs.onCustomMessage) {
        yjs.onCustomMessage(message);
      }
    };
    if (yjs && provider) {
      provider.connect();
      provider.on('customMessage', handleCustomMessage);
      const sharedType = doc.get('content', Y.XmlElement) as Y.XmlElement;
      withYjs(engine.current, sharedType, provider.awareness, {
        data: cursorUser ?? {
          name: 'Guest',
          color: '#000',
        },
      });
      if (onLoad) onLoad(engine.current, provider, isWebView);
    }
    
    试试这个 initValue 事件吧

**Comment by big-camel** [comment]
#340
