### ISSUE TITLE
Toolbar collapse item custome failured,  How can define success?

### ISSUE THREAD

**Issue by catacode** [red-axe/am-editor#362]
自定义toolbar-collapse的选项问，同样的配置一个有，一个没有，怎么配置让唤出的菜单都有，
配置是这样的：
```js
const collapseItems = [
  {
    name: 'image-uploader',
    className: 'btn-collapse',
    icon: 'image',
    title: '图片',
    search: '图片,tupian,image,img',
    onClick() {
      engine && engine.trigger('openImageStore')
      return false
    }
  },
  {
    name: Book.pluginName,
    className: 'iconfont icon-books',
    icon: '',
    title: '本子',
    type: 'dropdown',
    search: '本子,benzi,book',
    onClick() {
      engine && engine.trigger('openBookStore')
      return false
    }
  }, {
    name: 'codeblock',
    title: '代码'
  },
  'table',
  // 'file-uploader',
  // 'video-uploader',
  'math',
  'status',
]
```

这是菜单按钮唤出的，有book这个item：
![8757122699d284d0e5575000f79e44cf](https://github.com/red-axe/am-editor/assets/91318069/5824784d-708e-463f-b079-7f1c04201758)

这是 / 唤出的，没有本子这个item：
![image](https://github.com/red-axe/am-editor/assets/91318069/8b2759cf-1c2f-4f92-8aa9-2547012643e4)

**Comment by big-camel** [comment]
需要配置工具栏里面的 popup 属性列表

**Comment by catacode** [comment]
下拉菜单也用的是这个，全部配置如下：

```js
import type {
  PluginEntry,
  CardEntry,
  PluginOptions,
  NodeInterface,
  RangeInterface,
  EngineInterface,
} from "@aomao/engine";
// 插件
import Redo from "@aomao/plugin-redo";
import Undo from "@aomao/plugin-undo";
import Bold from "@aomao/plugin-bold";
import Code from "@aomao/plugin-code";
import Backcolor from "@aomao/plugin-backcolor";
import Fontcolor from "@aomao/plugin-fontcolor";
import Fontsize from "@aomao/plugin-fontsize";
import Italic from "@aomao/plugin-italic";
import Underline from "@aomao/plugin-underline";
import Hr, { HrComponent } from "@aomao/plugin-hr";
import Tasklist, { CheckboxComponent } from "@aomao/plugin-tasklist";
import Orderedlist from "@aomao/plugin-orderedlist";
import Unorderedlist from "@aomao/plugin-unorderedlist";
import Indent from "@aomao/plugin-indent";
import Heading from "@aomao/plugin-heading";
import Strikethrough from "@aomao/plugin-strikethrough";
import Sub from "@aomao/plugin-sub";
import Sup from "@aomao/plugin-sup";
import Alignment from "@aomao/plugin-alignment";
import Mark from "@aomao/plugin-mark";
import Quote from "@aomao/plugin-quote";
import PaintFormat from "@aomao/plugin-paintformat";
import RemoveFormat from "@aomao/plugin-removeformat";
import SelectAll from "@aomao/plugin-selectall";
import Link from "@aomao/plugin-link-vue";
import Codeblock, { CodeBlockComponent } from "@aomao/plugin-codeblock-vue";
import Image, { ImageComponent, ImageUploader } from "@aomao/plugin-image";
import Table, { TableComponent } from "@aomao/plugin-table";
// import File, { FileComponent, FileUploader } from "@aomao/plugin-file";
// import Video, { VideoComponent, VideoUploader } from "@aomao/plugin-video";
import Math, { MathComponent } from "@aomao/plugin-math";
import Fontfamily from "@aomao/plugin-fontfamily";
import Status, { StatusComponent } from "@aomao/plugin-status";
import LineHeight from "@aomao/plugin-line-height";
import Mention, { MentionComponent } from "@aomao/plugin-mention";
import MarkRange from "@aomao/plugin-mark-range";
import Book, { BookComponent } from './plugin/book'

import {
  ToolbarPlugin,
  ToolbarComponent,
  fontFamilyDefaultData,
} from "@aomao/toolbar-vue";

export const plugins: Array<PluginEntry> = [
  Redo,
  Undo,
  Bold,
  Code,
  Backcolor,
  Fontcolor,
  Fontsize,
  Italic,
  Underline,
  Hr,
  Tasklist,
  Orderedlist,
  Unorderedlist,
  Indent,
  Heading,
  Strikethrough,
  Sub,
  Sup,
  Alignment,
  Mark,
  Quote,
  PaintFormat,
  RemoveFormat,
  SelectAll,
  Link,
  Codeblock,
  Image,
  ImageUploader,
  Table,
  // File,
  // FileUploader,
  // Video,
  // VideoUploader,
  Math,
  ToolbarPlugin,
  Fontfamily,
  Status,
  LineHeight,
  Mention,
  MarkRange, // Cannot read properties of undefined (reading 'map'
  Book,
];

export const cards: Array<CardEntry> = [
  HrComponent,
  CheckboxComponent,
  CodeBlockComponent,
  ImageComponent,
  TableComponent,
  // FileComponent,
  // VideoComponent,
  MathComponent,
  ToolbarComponent,
  StatusComponent,
  MentionComponent,
  BookComponent,
];

let engine: EngineInterface | null = null;

export const setEngine = (e: EngineInterface) => {
  engine = e;
};

// collapse 菜单统一配置
const collapseItems = [
  {
    name: 'image-uploader',
    className: 'btn-collapse',
    icon: 'image',
    title: '图片',
    search: '图片,tupian,image,img',
    onClick() {
      engine && engine.trigger('openImageStore')
      return false
    }
  },
  {
    name: Book.pluginName,
    className: 'iconfont icon-books',
    icon: '',
    title: '本子',
    type: 'dropdown',
    search: '本子,benzi,book',
    onClick() {
      engine && engine.trigger('openBookStore')
      return false
    }
  }, {
    name: 'codeblock',
    title: '代码'
  },
  'table',
  // 'file-uploader',
  // 'video-uploader',
  'math',
  'status',
]

export const menu: Array<Array<any>> = [
  [{
    type: 'collapse',
    groups: [{
      items: collapseItems,
    }],
  }],
  ["heading", "fontfamily", "fontsize"],
  ["bold", "italic", "strikethrough", "underline"],
  ["fontcolor", "backcolor"],
  ["alignment"],
  ["unorderedlist", "orderedlist", "tasklist", "indent", "line-height"],
  ["link", "quote", "hr", "moremark"],
  ["undo", "redo", "paintformat", "removeformat"],
]

const apiPrefix = '/v1'

export const pluginConfig: { [key: string]: PluginOptions } = {
  [MarkRange.pluginName]: {
    keys: ["mark"],
    onChange: (
      addIds: { [key: string]: Array<string> },
      removeIds: { [key: string]: Array<string> }
    ) => {
      // 新增的标记
      const commentAddIds = addIds["comment"] || [];
      // 删除的标记
      const commentRemoveIds = removeIds["comment"] || [];
    },
    onSelect: (
      range: RangeInterface,
      selectInfo?: { key: string; id: string }
    ) => {
      const { key, id } = selectInfo || {};
      engine?.command.executeMethod(
        "mark-range",
        "action",
        "comment",
        "revoke"
      );
      if (key === "mark" && id) {
        engine?.command.executeMethod(
          "mark-range",
          "action",
          key,
          "preview",
          id
        );
      }
    },
  },
  [Italic.pluginName]: {
    markdown: "*",
  },
  [Image.pluginName]: {
    onBeforeRender: (status: string, url: string) => {
      if (url.startsWith("data:image/")) return url;
      return url;
    },
  },
  [ImageUploader.pluginName]: {
    file: {
      action: `${apiPrefix}/upload/image/file`,
      name: 'file',
      data: {
        title: '文章内容图片',
        categoryId: '130000',
        width: 280,
        height: 280,
        tags: '文章内容图片',
      },
      limitSize: 1024 * 1024 * 5,
      contentType: 'multipart/form-data',
    },
    remote: {
      action: `${apiPrefix}/upload/image/url`,
      name: 'file',
      data: {
        title: '文章内容图片',
        categoryId: '130000',
        tags: '文章内容图片',
      },
      limitSize: 1024 * 1024 * 5,
      contentType: 'multipart/form-data',
    },
    parse: (res: any) => {
      if (res.code === 0) {
        return { result: true, data: res.data.source };
      }
      return { result: false, data: '' };
    },
    isRemote: (src: string) => {
      return 'catebook.com'.indexOf(src) < 0
    }
  },
  // [FileUploader.pluginName]: {
  //   action: `${apiPrefix}/upload/file`,
  // },
  // [VideoUploader.pluginName]: {
  //   action: `${apiPrefix}/upload/video`,
  //   limitSize: 1024 * 1024 * 50,
  // },
  // [Video.pluginName]: {
  //   onBeforeRender: (status: string, url: string) => {
  //     return url;
  //   },
  // },
  [Math.pluginName]: {
    action: `${apiPrefix}/tool/latex`,
    parse: (res: any) => {
      if (res.code === 0) {
        return { result: true, data: res.data.file };
      }
      return { result: false, data: '' };
    },
  },
  [Mention.pluginName]: {
    action: `${apiPrefix}/friend/search`,
    onLoading: (root: NodeInterface) => {
      // const vm = createApp(Loading);
      // vm.mount(root.get<HTMLElement>()!);
    },
    onEmpty: (root: NodeInterface) => {
      // const vm = createApp(Empty);
      // vm.mount(root.get<HTMLElement>()!);
    },
    onClick: (
      root: NodeInterface,
      { key, name }: { key: string; name: string }
    ) => {
      console.log("mention click:", key, "-", name);
    },
    onMouseEnter: (
      layout: NodeInterface,
      { name }: { key: string; name: string }
    ) => {
      // const vm = createApp(MentionPopover, {
      //   name,
      // });
      // vm.mount(layout.get<HTMLElement>()!);
    },
  },
  [Fontsize.pluginName]: {
    //配置粘贴后需要过滤的字体大小
    filter: (fontSize: string) => {
      return (
        [
          "12px",
          "13px",
          "14px",
          "15px",
          "16px",
          "19px",
          "22px",
          "24px",
          "29px",
          "32px",
          "40px",
          "48px",
        ].indexOf(fontSize) > -1
      );
    },
  },
  [Fontfamily.pluginName]: {
    //配置粘贴后需要过滤的字体
    filter: (fontfamily: string) => {
      const item = fontFamilyDefaultData.find((item) =>
        fontfamily
          .split(",")
          .some(
            (name) =>
              item.value
                .toLowerCase()
                .indexOf(name.replace(/"/, "").toLowerCase()) > -1
          )
      );
      return item ? item.value : false;
    },
  },
  [LineHeight.pluginName]: {
    //配置粘贴后需要过滤的行高
    filter: (lineHeight: string) => {
      if (lineHeight === "14px") return "1";
      if (lineHeight === "16px") return "1.15";
      if (lineHeight === "21px") return "1.5";
      if (lineHeight === "28px") return "2";
      if (lineHeight === "35px") return "2.5";
      if (lineHeight === "42px") return "3";
      // 不满足条件就移除掉
      return ["1", "1.15", "1.5", "2", "2.5", "3"].indexOf(lineHeight) > -1;
    },
  },
  // 跟随鼠标拖蓝选中后的工具栏弹出框
  [ToolbarPlugin.pluginName]: {
    popup: {
      items: [
        {
          icon: 'text',
          items: [
            'bold',
            'italic',
            'strikethrough',
            'underline',
            'backcolor',
            'moremark',
          ]
        }
      ]
    },
    // 斜杠/下拉菜单的配置
    config: [{
      title: '常用内容',// 可选这里不显示
      items: collapseItems
    }],
  },
};
```

**Comment by big-camel** [comment]
toolbar 的 options 里面加上 popup 属性列表------------------------------------------------------------------
***@***.***>
日　期：2024年01月12日 19:40:33
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] Toolbar collapse item custome failured, How can define success? (Issue #362)

下拉菜单也用的是这个，全部配置如下：
import type {
  PluginEntry,
  CardEntry,
  PluginOptions,
  NodeInterface,
  RangeInterface,
  EngineInterface,
} from ***@***.***/engine";
// 插件
import Redo from ***@***.***/plugin-redo";
import Undo from ***@***.***/plugin-undo";
import Bold from ***@***.***/plugin-bold";
import Code from ***@***.***/plugin-code";
import Backcolor from ***@***.***/plugin-backcolor";
import Fontcolor from ***@***.***/plugin-fontcolor";
import Fontsize from ***@***.***/plugin-fontsize";
import Italic from ***@***.***/plugin-italic";
import Underline from ***@***.***/plugin-underline";
import Hr, { HrComponent } from ***@***.***/plugin-hr";
import Tasklist, { CheckboxComponent } from ***@***.***/plugin-tasklist";
import Orderedlist from ***@***.***/plugin-orderedlist";
import Unorderedlist from ***@***.***/plugin-unorderedlist";
import Indent from ***@***.***/plugin-indent";
import Heading from ***@***.***/plugin-heading";
import Strikethrough from ***@***.***/plugin-strikethrough";
import Sub from ***@***.***/plugin-sub";
import Sup from ***@***.***/plugin-sup";
import Alignment from ***@***.***/plugin-alignment";
import Mark from ***@***.***/plugin-mark";
import Quote from ***@***.***/plugin-quote";
import PaintFormat from ***@***.***/plugin-paintformat";
import RemoveFormat from ***@***.***/plugin-removeformat";
import SelectAll from ***@***.***/plugin-selectall";
import Link from ***@***.***/plugin-link-vue";
import Codeblock, { CodeBlockComponent } from ***@***.***/plugin-codeblock-vue";
import Image, { ImageComponent, ImageUploader } from ***@***.***/plugin-image";
import Table, { TableComponent } from ***@***.***/plugin-table";
// import File, { FileComponent, FileUploader } from ***@***.***/plugin-file";
// import Video, { VideoComponent, VideoUploader } from ***@***.***/plugin-video";
import Math, { MathComponent } from ***@***.***/plugin-math";
import Fontfamily from ***@***.***/plugin-fontfamily";
import Status, { StatusComponent } from ***@***.***/plugin-status";
import LineHeight from ***@***.***/plugin-line-height";
import Mention, { MentionComponent } from ***@***.***/plugin-mention";
import MarkRange from ***@***.***/plugin-mark-range";
import Book, { BookComponent } from './plugin/book'

import {
  ToolbarPlugin,
  ToolbarComponent,
  fontFamilyDefaultData,
} from ***@***.***/toolbar-vue";

export const plugins: Array<PluginEntry> = [
  Redo,
  Undo,
  Bold,
  Code,
  Backcolor,
  Fontcolor,
  Fontsize,
  Italic,
  Underline,
  Hr,
  Tasklist,
  Orderedlist,
  Unorderedlist,
  Indent,
  Heading,
  Strikethrough,
  Sub,
  Sup,
  Alignment,
  Mark,
  Quote,
  PaintFormat,
  RemoveFormat,
  SelectAll,
  Link,
  Codeblock,
  Image,
  ImageUploader,
  Table,
  // File,
  // FileUploader,
  // Video,
  // VideoUploader,
  Math,
  ToolbarPlugin,
  Fontfamily,
  Status,
  LineHeight,
  Mention,
  MarkRange, // Cannot read properties of undefined (reading 'map'
  Book,
];

export const cards: Array<CardEntry> = [
  HrComponent,
  CheckboxComponent,
  CodeBlockComponent,
  ImageComponent,
  TableComponent,
  // FileComponent,
  // VideoComponent,
  MathComponent,
  ToolbarComponent,
  StatusComponent,
  MentionComponent,
  BookComponent,
];

let engine: EngineInterface | null = null;

export const setEngine = (e: EngineInterface) => {
  engine = e;
};

// collapse 菜单统一配置
const collapseItems = [
  {
    name: 'image-uploader',
    className: 'btn-collapse',
    icon: 'image',
    title: '图片',
    search: '图片,tupian,image,img',
    onClick() {
      engine && engine.trigger('openImageStore')
      return false
    }
  },
  {
    name: Book.pluginName,
    className: 'iconfont icon-books',
    icon: '',
    title: '本子',
    type: 'dropdown',
    search: '本子,benzi,book',
    onClick() {
      engine && engine.trigger('openBookStore')
      return false
    }
  }, {
    name: 'codeblock',
    title: '代码'
  },
  'table',
  // 'file-uploader',
  // 'video-uploader',
  'math',
  'status',
]

export const menu: Array<Array<any>> = [
  [{
    type: 'collapse',
    groups: [{
      items: collapseItems,
    }],
  }],
  ["heading", "fontfamily", "fontsize"],
  ["bold", "italic", "strikethrough", "underline"],
  ["fontcolor", "backcolor"],
  ["alignment"],
  ["unorderedlist", "orderedlist", "tasklist", "indent", "line-height"],
  ["link", "quote", "hr", "moremark"],
  ["undo", "redo", "paintformat", "removeformat"],
]

const apiPrefix = '/v1'

export const pluginConfig: { [key: string]: PluginOptions } = {
  [MarkRange.pluginName]: {
    keys: ["mark"],
    onChange: (
      addIds: { [key: string]: Array<string> },
      removeIds: { [key: string]: Array<string> }
    ) => {
      // 新增的标记
      const commentAddIds = addIds["comment"] || [];
      // 删除的标记
      const commentRemoveIds = removeIds["comment"] || [];
    },
    onSelect: (
      range: RangeInterface,
      selectInfo?: { key: string; id: string }
    ) => {
      const { key, id } = selectInfo || {};
      engine?.command.executeMethod(
        "mark-range",
        "action",
        "comment",
        "revoke"
      );
      if (key === "mark" && id) {
        engine?.command.executeMethod(
          "mark-range",
          "action",
          key,
          "preview",
          id
        );
      }
    },
  },
  [Italic.pluginName]: {
    markdown: "*",
  },
  [Image.pluginName]: {
    onBeforeRender: (status: string, url: string) => {
      if (url.startsWith("data:image/")) return url;
      return url;
    },
  },
  [ImageUploader.pluginName]: {
    file: {
      action: `${apiPrefix}/upload/image/file`,
      name: 'file',
      data: {
        title: '文章内容图片',
        categoryId: '130000',
        width: 280,
        height: 280,
        tags: '文章内容图片',
      },
      limitSize: 1024 * 1024 * 5,
      contentType: 'multipart/form-data',
    },
    remote: {
      action: `${apiPrefix}/upload/image/url`,
      name: 'file',
      data: {
        title: '文章内容图片',
        categoryId: '130000',
        tags: '文章内容图片',
      },
      limitSize: 1024 * 1024 * 5,
      contentType: 'multipart/form-data',
    },
    parse: (res: any) => {
      if (res.code === 0) {
        return { result: true, data: res.data.source };
      }
      return { result: false, data: '' };
    },
    isRemote: (src: string) => {
      return 'catebook.com'.indexOf(src) < 0
    }
  },
  // [FileUploader.pluginName]: {
  //   action: `${apiPrefix}/upload/file`,
  // },
  // [VideoUploader.pluginName]: {
  //   action: `${apiPrefix}/upload/video`,
  //   limitSize: 1024 * 1024 * 50,
  // },
  // [Video.pluginName]: {
  //   onBeforeRender: (status: string, url: string) => {
  //     return url;
  //   },
  // },
  [Math.pluginName]: {
    action: `${apiPrefix}/tool/latex`,
    parse: (res: any) => {
      if (res.code === 0) {
        return { result: true, data: res.data.file };
      }
      return { result: false, data: '' };
    },
  },
  [Mention.pluginName]: {
    action: `${apiPrefix}/friend/search`,
    onLoading: (root: NodeInterface) => {
      // const vm = createApp(Loading);
      // vm.mount(root.get<HTMLElement>()!);
    },
    onEmpty: (root: NodeInterface) => {
      // const vm = createApp(Empty);
      // vm.mount(root.get<HTMLElement>()!);
    },
    onClick: (
      root: NodeInterface,
      { key, name }: { key: string; name: string }
    ) => {
      console.log("mention click:", key, "-", name);
    },
    onMouseEnter: (
      layout: NodeInterface,
      { name }: { key: string; name: string }
    ) => {
      // const vm = createApp(MentionPopover, {
      //   name,
      // });
      // vm.mount(layout.get<HTMLElement>()!);
    },
  },
  [Fontsize.pluginName]: {
    //配置粘贴后需要过滤的字体大小
    filter: (fontSize: string) => {
      return (
        [
          "12px",
          "13px",
          "14px",
          "15px",
          "16px",
          "19px",
          "22px",
          "24px",
          "29px",
          "32px",
          "40px",
          "48px",
        ].indexOf(fontSize) > -1
      );
    },
  },
  [Fontfamily.pluginName]: {
    //配置粘贴后需要过滤的字体
    filter: (fontfamily: string) => {
      const item = fontFamilyDefaultData.find((item) =>
        fontfamily
          .split(",")
          .some(
            (name) =>
              item.value
                .toLowerCase()
                .indexOf(name.replace(/"/, "").toLowerCase()) > -1
          )
      );
      return item ? item.value : false;
    },
  },
  [LineHeight.pluginName]: {
    //配置粘贴后需要过滤的行高
    filter: (lineHeight: string) => {
      if (lineHeight === "14px") return "1";
      if (lineHeight === "16px") return "1.15";
      if (lineHeight === "21px") return "1.5";
      if (lineHeight === "28px") return "2";
      if (lineHeight === "35px") return "2.5";
      if (lineHeight === "42px") return "3";
      // 不满足条件就移除掉
      return ["1", "1.15", "1.5", "2", "2.5", "3"].indexOf(lineHeight) > -1;
    },
  },
  // 跟随鼠标拖蓝选中后的工具栏弹出框
  [ToolbarPlugin.pluginName]: {
    popup: {
      items: [
        {
          icon: 'text',
          items: [
            'bold',
            'italic',
            'strikethrough',
            'underline',
            'backcolor',
            'moremark',
          ]
        }
      ]
    },
    // 斜杠/下拉菜单的配置
    config: [{
      title: '常用内容',// 可选这里不显示
      items: collapseItems
    }],
  },
};

**Comment by catacode** [comment]
帮忙看看，哪个popup是选中后弹出的框，不是 / 唤出的菜单。

**Comment by big-camel** [comment]
toolbar options 的 config 选项？

**Comment by catacode** [comment]
对的，我看配置那个位置会影响 / 唤出的菜单，但是增减自定义的就不受影响，默认有的那个几个，增减是会有效果的。

**Comment by big-camel** [comment]
配置不是通用的，也需要去config那里再配置一次

**Comment by catacode** [comment]
这里配置菜单部分的，
<am-toolbar v-if="engine" :engine="engine" :items="menu" />

然后这里配置 / 唤出的菜单：
 pluginConfig 的config.items，

这两个地方都配置了，你说的是这个吗？

**Comment by catacode** [comment]
1. pluginConfig配置的config.items里配置 / 唤出的菜单

2. `<am-toolbar v-if="engine" :engine="engine" :items="menu" />`这里menu的collapse配置菜单按钮唤出的菜单

是这样的对吗？我都配置了，2边的参数都一样的，增减默认的菜单是有效的，如upload-image。但是增减我自定义的plugin，/ 唤出的菜单里，就不出现我自定义的那个item。

**Comment by big-camel** [comment]
确认你的插件已经配置到 plugins 里面了吗?

**Comment by catacode** [comment]
是的，确实是配置到里边了，菜单部分正常，就 / 唤出没有。

![7c93d653c1aabb69558a6d0fd5d140dd](https://github.com/red-axe/am-editor/assets/91318069/0334a7be-2008-4011-9d85-96acc90da07e)

**Comment by catacode** [comment]
我看有些插件进不去collapse里边，我尝试了hr和link，好像不让出现在collapse。是有plugin类型限制吗？或者需要设置个什么属性？

**Comment by catacode** [comment]
vue3

**Comment by catacode** [comment]
"@aomao/engine": "^2.9",
"vue": "^3.3.4",

**Comment by big-camel** [comment]
我看代码逻辑确实没啥问题
只能你那边debug看看了，f12 debug node_modules 里面的 toolbar-vue 插件中的代码，找到这个 getData 代码
![image](https://github.com/red-axe/am-editor/assets/55792257/7f9bc18f-0c64-4054-8a87-031b05c7d628)

**Comment by catacode** [comment]
找到这个文件文件了，打了console.log, 但是浏览器并没有输出调试结果

方便微信或者qq找你不？我加你

**Comment by big-camel** [comment]
浏览器上debug，如果直接 console.log ，你需要重新启动项目，不然vue加载的仍然是缓存的 node_modules 内的文件

**Comment by catacode** [comment]
打了个调试日志断点，看输出 是有个这个数据的。

![0798b2bdd83ad7458594996368d8b3ec](https://github.com/red-axe/am-editor/assets/91318069/171a1b1f-a58c-43d8-a359-dc1819e65da0)
![35d81f0f2203b511bb49714e25549edf](https://github.com/red-axe/am-editor/assets/91318069/7ec2ab0d-a761-4d34-b45e-93ff2d074203)

**Comment by big-camel** [comment]
然后继续到渲染的那一步

**Comment by catacode** [comment]
getData 函数把book的配置项，过滤掉了，配置有，但是返回不包含这个数据了。

![80706f824b18602f7d9be15261c6df6e](https://github.com/red-axe/am-editor/assets/91318069/f9951b78-543a-44ea-9109-bdc0e3246e84)
![a93573274e4306a553343e6be8c06e2c](https://github.com/red-axe/am-editor/assets/91318069/c3cfd161-692d-4891-ab8a-667827b43598)

**Comment by big-camel** [comment]
不是的，后面 items.push 这里只是覆盖配置而已

**Comment by catacode** [comment]
camel,有处理建议吗？

**Comment by big-camel** [comment]
继续往下，到渲染那里看看

**Comment by catacode** [comment]
渲染部分没有新增的数据
![4c41e2408c0e921b2239e067c2ac160a](https://github.com/red-axe/am-editor/assets/91318069/44b1f32f-d43e-4166-87d7-85734792c05c)

**Comment by big-camel** [comment]
在跟踪 data 在哪里变化了吧

**Comment by catacode** [comment]
就是这里把新增的选项过滤掉了。

![5ad23dd85abb0c74fb02c0027322a582](https://github.com/red-axe/am-editor/assets/91318069/1b9e1681-f6e4-4944-b1e5-f6e95fabd69e)

**Comment by big-camel** [comment]
https://www.npmjs.com/package/@aomao/toolbar-vue/v/2.9.36?activeTab=code

那就升级版本吧，从 2.9 的最后一个版本可以看到下面的 else
![image](https://github.com/red-axe/am-editor/assets/55792257/1ee92b51-7818-436b-ae7d-7a0cbd97c6fa)

**Comment by catacode** [comment]
版本设计2.10后，确实有数据了，感谢

不过报错了，不影响正常使用。

<img width="671" alt="image" src="https://github.com/red-axe/am-editor/assets/91318069/3def6e3a-0ec9-48f3-8ced-a9d55762c57e">
