### ISSUE TITLE
批量上传会丢失数据 request.upload方法有错误

### ISSUE THREAD

**Issue by chunyangyang** [red-axe/am-editor#366]
源码位置：packages\engine\src\request\uploader\index.ts
![image](https://github.com/red-axe/am-editor/assets/20843521/4e269d6c-45a3-459a-b461-25dda52e259d)
这样会导致files变化数据获取错误，导致丢失建议写法，当然其他写法也可以，保证获取到需要上传的数据就行
![image](https://github.com/red-axe/am-editor/assets/20843521/c27d3492-e852-4729-962d-8ec0396053b4)

**Comment by big-camel** [comment]
建议提交pr
