### ISSUE TITLE
建议添加流程图插件，并且适配markdown类型

### ISSUE THREAD

**Issue by lilingshan** [red-axe/am-editor#49]
md：
```flow
st=>start: 开始框
op=>operation: 处理框
cond=>condition: 判断框(是或否?)
sub1=>subroutine: 子流程
io=>inputoutput: 输入输出框
e=>end: 结束框
st->op->cond
cond(yes)->io->e
cond(no)->sub1(right)->op
```

![image](https://user-images.githubusercontent.com/51754620/140616662-f127395e-a080-46ef-88ee-f8f16fb44e2b.png)

**Comment by yanmao-cc** [comment]
这里几个 https://drawing.aomao.com/ 生成相关图的api

**Comment by zhaodeezhu** [comment]
不知道结合drawio实现的绘图功能能不能满足需求
相关介绍的公众号：
[drawio和am-editor强强联合，实现强大的富文本编辑器绘图板块](https://mp.weixin.qq.com/s?__biz=Mzg3NjE2MDI1NA==&mid=2247483699&idx=1&sn=8b1cb57cea0002c35832067a956d6e66&chksm=cf3734a2f840bdb4cddc037153b55e011bf5273caa196bfa75c71cec30b6a064e1495bdf6cbf#rd)
示例项目：
[xioo-docs](https://github.com/zhaodeezhu/xioo-docs)
