### ISSUE TITLE
你好，我这边出现了从挂载插件页面回退后导致回退后的页面会有样式改变的情况

### ISSUE THREAD

**Issue by jyp0912** [red-axe/am-editor#52]
我从A页面跳转到B页面（挂载插件）后，返回到A页面，发现A页面有些样式的改变，如图中对勾的变化
![FireShot Capture 008 - ssp-cm vue - localhost](https://user-images.githubusercontent.com/50137176/141087547-c68876b0-48d8-4acb-acc1-8053fb3fb89a.png)

![FireShot Capture 009 - ssp-cm vue - localhost](https://user-images.githubusercontent.com/50137176/141087556-a6fbe384-c25f-4205-bd55-9b1b9a806148.png)

**Comment by yanmao-cc** [comment]
这个应该会经过一个生命周期吧，unmount 中有 engine.destroy() 吗

**Comment by jyp0912** [comment]
有的，好像是engine.value.destroy。不过第一次进的时候确实有一点卡顿，后面再进就不会有那个卡一下的感觉。
