### ISSUE TITLE
希望可以提供类似语雀的表格、脑图、流程图的支持

### ISSUE THREAD

**Issue by gudaoxuri** [red-axe/am-editor#65]
![69c14309d79938af58b997622cd3b39](https://user-images.githubusercontent.com/2802567/147313301-9280e12e-52a5-4f9b-8030-efc14ad8dcca.png)

如上，希望能提供类似的插件化支持。谢谢。

**Comment by yanmao-cc** [comment]
这里有个几个 https://drawing.aomao.com/ 生成相关图的api
