### ISSUE TITLE
有没有类似这种快捷标题导航

### ISSUE THREAD

**Issue by zhaodeezhu** [red-axe/am-editor#73]
![image](https://user-images.githubusercontent.com/58294623/149249536-f4eb334d-b2d2-43c8-a2ce-ff542ba49f88.png)

看到官网在编辑模式下是有的，查看模式下没有，是要自己去实现吗，还是有此插件
没有找到相关文档

![image](https://user-images.githubusercontent.com/58294623/149249713-581c8753-dee5-4405-9a9e-6160942b97ad.png)

**Comment by yanmao-cc** [comment]
https://editor.aomao.com/zh-CN/plugin/plugin-heading#normalize 这个就是拿到h节点的数据，然后渲染出来就好了
