### ISSUE TITLE
协同编辑后，如何实现track change功能？编辑器获取的html或json 没有编辑者的信息。

### ISSUE THREAD

**Issue by ghost** [red-axe/am-editor#79]
![图片](https://user-images.githubusercontent.com/13491541/150454936-a5b125ab-c9ca-47b6-ab45-1310191ed45d.png)

**Comment by yanmao-cc** [comment]
这个可以在 ot-server 里面的 sharedb 和数据库看一下，

**Comment by 13826503448** [comment]
好的，如果有实现思路回头更新，感谢你的回复。
