### ISSUE TITLE
导入markdown字符串可以自动解析出am-editor的展示

### ISSUE THREAD

**Issue by zhaodeezhu** [red-axe/am-editor#87]
使用方法：
<img width="350" alt="image" src="https://user-images.githubusercontent.com/58294623/153742940-1f30d134-989f-4541-8d04-848e217dc497.png">
效果：
<img width="278" alt="image" src="https://user-images.githubusercontent.com/58294623/153743015-a2e586ca-a279-40db-aed5-a42469fe5b22.png">

我是使用setValue方法设置markdown语法的字符串，发现不能解析出展示，这个功能主要是想实现导入功能，原来其他的markdown写好的文件可以直接导入进来，使用某个方法设置到里面就可以保存了，为了方便用户迁移

**Comment by yanmao-cc** [comment]
setHtml 试一下，或者先转换成html再调用 setHtml

**Comment by zhaodeezhu** [comment]
> setHtml 试一下，或者先转换成html再调用 setHtml

你好，setHtml是不行的，转换成html是要我自己解析 文本 转换成html吗，还是有对应的方法可以将 markdown的文本转换成html?
例如我传入的文本是 # 001，自动转成 <h1>001</h1>

**Comment by yanmao-cc** [comment]
2.7.29 使用 engine.setMarkdown 看看

**Comment by zhaodeezhu** [comment]
非常感谢作者，这么晚还在回复。
版本好像还没有发布，现在最高还是 .28

**Comment by yanmao-cc** [comment]
好了

**Comment by zhaodeezhu** [comment]
可以了，感谢作者
