### ISSUE TITLE
能支持导出word吗？

### ISSUE THREAD

**Issue by yswang0927** [red-axe/am-editor#88]
am-editor 编辑的内容能提供导出为 word(docx) 的功能吗？

**Comment by yanmao-cc** [comment]
可以使用getHtml 获取到html，然后使用其它方法转

**Comment by yswang0927** [comment]
html -> docx 效果并不好， 能获取到非 html 数据（比如：json格式数据）吗？然后在后台按照数据格式含义进行转换为docx的格式。

**Comment by yanmao-cc** [comment]
可以使用 engine.getJsonValue() 获取json

**Comment by byoungd** [comment]
> html -> docx 效果并不好， 能获取到非 html 数据（比如：json格式数据）吗？然后在后台按照数据格式含义进行转换为docx的格式。

后续会考虑提供导出插件 WIP

**Comment by starsoul666** [comment]
> > html -> docx 效果并不好， 能获取到非 html 数据（比如：json格式数据）吗？然后在后台按照数据格式含义进行转换为docx的格式。
> 
> 后续会考虑提供导出插件 WIP

导出插件有啥计划吗？

**Comment by big-camel** [comment]
获取到html自己转换------------------------------------------------------------------
***@***.***>
日　期：2024年03月28日 18:16:39
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [red-axe/am-editor] 能支持导出word吗？ (Issue #88)

 
html -> docx 效果并不好， 能获取到非 html 数据（比如：json格式数据）吗？然后在后台按照数据格式含义进行转换为docx的格式。 
后续会考虑提供导出插件 WIP 
导出插件有啥计划吗？
