### ISSUE TITLE
后端ot-serve跑步起来呀！大佬你们确定能跑起来吗

### ISSUE THREAD

**Issue by JackFrancisLiu** [red-axe/am-editor#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by yanmao-cc** [comment]
mongodb 安装了吗？有啥错误信息吗？

**Comment by JackFrancisLiu** [comment]
> mongodb 安装了吗？有啥错误信息吗？

![1645001726(1)](https://user-images.githubusercontent.com/25114528/154229726-43cca024-8f06-419c-9f6d-170ed0130784.jpg)

**Comment by JackFrancisLiu** [comment]
> > mongodb 安装了吗？有啥错误信息吗？
> 
> ![1645001726(1)](https://user-images.githubusercontent.com/25114528/154229726-43cca024-8f06-419c-9f6d-170ed0130784.jpg)

启动ot-server就是这样，空白页面啊，怎么连接呢请问

**Comment by yanmao-cc** [comment]
ot-server 本来就没有页面的。。。就单纯的ws连接

**Comment by JackFrancisLiu** [comment]
> ot-server 本来就没有页面的。。。就单纯的ws连接

new OTClient(engine); 这个otclient去哪里引用，老板。

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/ot/client.ts

**Comment by JackFrancisLiu** [comment]
> https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/ot/client.ts

![1645005101(1)](https://user-images.githubusercontent.com/25114528/154239417-95d247f2-4b48-4a66-94b7-950848eb59e6.jpg)
sharedb这个包安装后有些目录是找不到的，你的文档是不是该更新了，老板

**Comment by yanmao-cc** [comment]
应该类型问题吧， import type { Doc } from 'sharedb'
import type { Socket } from 'sharedb/lib/sharedb'
现在vue和react 混合的，有些东西失效了，后面会分隔开。

**Comment by JackFrancisLiu** [comment]
> 

node_module的包里面就没有sharedb/lib/sharedb这个路径呀

**Comment by JackFrancisLiu** [comment]
> 应该类型问题吧， import type { Doc } from 'sharedb' import type { Socket } from 'sharedb/lib/sharedb' 现在vue和react 混合的，有些东西失效了，后面会分隔开。

或者说sharedb用的哪个版本，我安装下特定版本

**Comment by yanmao-cc** [comment]
1.9 以上都可以

**Comment by JackFrancisLiu** [comment]
> 1.9 以上都可以
一直报错，有空可以看下，反正我这里都是报错，说明是找不到包。下班了

**Comment by JackFrancisLiu** [comment]
> 1.9 以上都可以

为什么不把otclient做成一个npm包呢，这样不是更方便

**Comment by yanmao-cc** [comment]
因为里面可以定制化的东西还是有些的，就一个文件，也不大

**Comment by yanmao-cc** [comment]
换成这个  
import type { Doc } from 'sharedb' 
import type { Socket } from 'sharedb/lib/sharedb' ‘
导入不行吗？

**Comment by JackFrancisLiu** [comment]
> 换成这个 import type { Doc } from 'sharedb' import type { Socket } from 'sharedb/lib/sharedb' ‘ 导入不行吗？

如果是ts就可以，请问下有没有js版本的otclient，再用vue2开发

**Comment by yanmao-cc** [comment]
js 那你直接把这些类型的删掉就好了

**Comment by JackFrancisLiu** [comment]
> js 那你直接把这些类型的删掉就好了

我想问下初始化协同编辑的内容去哪里配置，就是调用接口获取文档内容，接口怎么配置，老板

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/index.tsx#L180

**Comment by JackFrancisLiu** [comment]
> https://github.com/red-axe/am-editor/blob/master/examples/react/components/editor/index.tsx#L180

等你的vue版本吧，太难了，我发现ot-server没有保存文档内容呀！也没有广播文档内容吧

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor-vue

广播以及保存可以看看sharedb

**Comment by JackFrancisLiu** [comment]
> https://github.com/red-axe/am-editor-vue
> 
> 广播以及保存可以看看sharedb

ot-serve服务已经启动了，没发现保存内容的表呀！如图
![1645083726(1)](https://user-images.githubusercontent.com/25114528/154428836-35f97814-5101-4b3d-81f2-2520ab71378d.jpg)

**Comment by yanmao-cc** [comment]
一个op记录表，一个数据表。都是json格式的数据

**Comment by JackFrancisLiu** [comment]
> 一个op记录表，一个数据表。都是json格式的数据

有没有vue带协同编辑的demo，然后和ot-server启动就能一起协同编辑，这种完整的demo要不要搞一个，老板。不然vue2协同编辑不能搞啊！获取不到数据库数据，也不能协同

**Comment by yanmao-cc** [comment]
vue 也是一样的，ot-client 就是一段js，实例化对接就行了。。。后续有时间再写吧

**Comment by JackFrancisLiu** [comment]
> vue 也是一样的，ot-client 就是一段js，实例化对接就行了。。。后续有时间再写吧

这个！运算符是不是不应该加。
![1645149600(1)](https://user-images.githubusercontent.com/25114528/154603325-08ba4571-6dd7-460c-9c2f-9c489d02dcf2.jpg)

**Comment by JackFrancisLiu** [comment]
> vue 也是一样的，ot-client 就是一段js，实例化对接就行了。。。后续有时间再写吧

初始值为空的话，文档引擎会报错。
![1645153256(1)](https://user-images.githubusercontent.com/25114528/154609695-76f133be-285f-4293-a968-f78685d92b55.jpg)
![1645153312(1)](https://user-images.githubusercontent.com/25114528/154609704-c83e2dc3-914c-4a00-9b6e-73a3f490da26.jpg)

**Comment by yanmao-cc** [comment]
defaultValue.value 而不是 defaultValue

**Comment by JackFrancisLiu** [comment]
> defaultValue.value 而不是 defaultValue

老板，可以协同编辑了，牛逼666
