### ISSUE TITLE
表格无法进行单元格选中合并

### ISSUE THREAD

**Issue by keepfit123** [red-axe/am-editor#97]

**Comment by yanmao-cc** [comment]
没测出来，如何复现？

**Comment by keepfit123** [comment]
[我用的是火狐浏览器（360极速浏览器没问题），鼠标选中单元格移动时有时候能够选中成功，但是会弹出多个“复制”提示。
![单元格选中](https://user-images.githubusercontent.com/98519430/154648151-1293d0e3-1be7-428b-b733-737d81ca17b2.png)

**Comment by byoungd** [comment]
> _No description provided._

请提供详细的描述或者补充截图进行说明，谢谢！

**Comment by yanmao-cc** [comment]
复制成功提示没复现，火狐除了第一行拖动会选中，其它没有拖动效果

**Comment by yanmao-cc** [comment]
https://github.com/red-axe/am-editor/releases/tag/%40aomao%2Fengine%402.7.33
