### ISSUE TITLE
fontsize 设置默认字体好像不生效

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#98]
我用命令的方式设置默认字体不生效，还有没有其他方式加默认字体呢？

**Comment by smallCF** [comment]
![image](https://user-images.githubusercontent.com/50435732/154874421-c9cc8414-92d9-42cb-aa15-eeefbbd52175.png)
这里的这个默认字体，我想更改一下

**Comment by yanmao-cc** [comment]
默认字体大小配置一下工具栏的配置
```ts
[Fontsize.pluginName]: {
    defaultSize: '16px',
}
```
其次就是把 am-engine 的跟节点样式增加font-size:16px。执行默认字体大小命令就是去除文字节点的font-size样式
