### ISSUE TITLE
编辑情况下，表格有时候会一直loadiing

### ISSUE THREAD

**Issue by smallCF** [red-axe/am-editor#99]
![image](https://user-images.githubusercontent.com/50435732/154875052-6976f08c-0856-4bd4-a685-4aa6dc756c28.png)
这种一直在loading，加载不出来内容，预览的情况是可以

**Comment by smallCF** [comment]
![image](https://user-images.githubusercontent.com/50435732/154875091-4496a8ba-823c-422d-aafa-87e4237ab53e.png)

**Comment by yanmao-cc** [comment]
可以看看 https://editor.aomao.com/config#scrollnode 这个设置，滚动节点高度是否撑满了编辑器视界界面，因为现在 表格、代码块 是默认设置了 https://editor.aomao.com/config#lazyrender 懒加载，在视图可见的时候才会去加载。

第二个可以先把 lazyrender 关了也可以

**Comment by smallCF** [comment]
感谢，我试一下
